import json, os, re, subprocess, tempfile
from datetime import datetime, timezone
from pathlib import Path

def now(): return datetime.now(timezone.utc).isoformat()
def read_json(path, default=None):
    if default is None: default={}
    try: return json.loads(Path(path).read_text(encoding='utf-8'))
    except Exception: return default
def write_json(path, data):
    path=Path(path); path.parent.mkdir(parents=True, exist_ok=True)
    fd,tmp=tempfile.mkstemp(dir=str(path.parent),prefix=path.name+'.')
    try:
        with os.fdopen(fd,'w',encoding='utf-8') as f:
            json.dump(data,f,indent=2,sort_keys=True,default=str); f.flush(); os.fsync(f.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)
def append_jsonl(path, data):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    with path.open('a',encoding='utf-8') as f: f.write(json.dumps(data,sort_keys=True,default=str)+'\n')
def slugify(value): return re.sub(r'[^a-z0-9]+','-',str(value).lower()).strip('-') or 'venture'

class VentureBuilder:
    def __init__(self, home):
        self.home=Path(home)
        self.runtime=self.home/'companyos_runtime'/'venture_builder_80001_95000'
        self.runtime.mkdir(parents=True,exist_ok=True)
    def run(self):
        src=self.home/'companyos_runtime'/'roadmap_execution_70001_80000'/'active_execution.json'
        raw=read_json(src,{})
        execution=raw.get('execution',raw)
        if not execution: return {'status':'idle','reason':'no linked execution'}
        subject=execution.get('subject') or 'digital template business'
        execution_id=execution.get('execution_id') or 'exec-'+slugify(subject)
        workspace=self.home/'generated_ventures'/slugify(subject)
        claim={'execution_id':execution_id,'subject':subject,'state':'CLAIMED','progress_percent':20,'updated_at':now()}
        write_json(self.runtime/'active_build.json',claim)
        spec={'execution_id':execution_id,'subject':subject,'venture_type':'digital_product','target_customer':'small businesses and independent professionals','problem':'Customers need practical reusable templates that save time.','offer':'A focused digital-template bundle with clear outcomes and instructions.','mvp':['landing page','template catalog','sample template','support documentation'],'acceptance_criteria':['workspace exists','website exists','API file exists','tests pass','launch checklist exists'],'external_actions':'review_required','generated_at':now()}
        write_json(self.runtime/'specification.json',spec)
        for folder in ['website','api','docs','tests','artifacts']:(workspace/folder).mkdir(parents=True,exist_ok=True)
        write_json(workspace/'specification.json',spec)
        (workspace/'README.md').write_text('# '+subject+'\n\nGenerated by CompanyOS Venture Builder.\n',encoding='utf-8')
        (workspace/'docs'/'business_plan.md').write_text('# Business plan\n\n## Customer\n'+spec['target_customer']+'\n\n## Problem\n'+spec['problem']+'\n\n## Offer\n'+spec['offer']+'\n',encoding='utf-8')
        (workspace/'docs'/'launch_checklist.md').write_text('- [ ] Confirm offer\n- [ ] Review legal/payment configuration\n- [ ] Approve external deployment\n- [ ] Verify analytics\n',encoding='utf-8')
        html='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+subject+'</title><style>body{font-family:system-ui;background:#0b1020;color:#eef2ff;margin:0}main{max-width:900px;margin:auto;padding:48px 24px}.card{background:#151d33;padding:24px;border-radius:18px;margin:20px 0}</style></head><body><main><h1>'+subject+'</h1><div class="card"><h2>Save time with practical templates</h2><p>A focused starter storefront generated by CompanyOS.</p></div></main></body></html>'
        (workspace/'website'/'index.html').write_text(html,encoding='utf-8')
        api="""from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
import json
class H(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path=='/health':
            body=json.dumps({'ok':True}).encode(); self.send_response(200); self.send_header('Content-Type','application/json'); self.send_header('Content-Length',str(len(body))); self.end_headers(); self.wfile.write(body)
        else: self.send_response(404); self.end_headers()
if __name__=='__main__': ThreadingHTTPServer(('127.0.0.1',8891),H).serve_forever()
"""
        (workspace/'api'/'server.py').write_text(api,encoding='utf-8')
        test="""import unittest
from pathlib import Path
class T(unittest.TestCase):
    def test_files(self):
        r=Path(__file__).resolve().parents[1]
        self.assertTrue((r/'website'/'index.html').exists())
        self.assertTrue((r/'api'/'server.py').exists())
        self.assertTrue((r/'specification.json').exists())
if __name__=='__main__': unittest.main()
"""
        (workspace/'tests'/'test_workspace.py').write_text(test,encoding='utf-8')
        cp=subprocess.run(['python','-m','unittest','discover','-s','tests','-v'],cwd=workspace,text=True,capture_output=True)
        checks={'workspace_exists':workspace.exists(),'website_exists':(workspace/'website'/'index.html').exists(),'api_exists':(workspace/'api'/'server.py').exists(),'checklist_exists':(workspace/'docs'/'launch_checklist.md').exists(),'tests_passed':cp.returncode==0}
        passed=all(checks.values())
        state={'execution_id':execution_id,'subject':subject,'state':'READY_FOR_REVIEW' if passed else 'VALIDATING','current_step':'internal_validation_complete' if passed else 'validation_required','progress_percent':90 if passed else 75,'workspace':str(workspace),'checks':checks,'updated_at':now()}
        write_json(self.runtime/'build_state.json',state); write_json(workspace/'build_state.json',state)
        queue=read_json(self.runtime/'deployment_queue.json',{'items':[]})
        if passed and not any(i.get('execution_id')==execution_id for i in queue['items']): queue['items'].append({'execution_id':execution_id,'subject':subject,'workspace':str(workspace),'state':'AWAITING_EXTERNAL_REVIEW','queued_at':now()})
        write_json(self.runtime/'deployment_queue.json',queue)
        live={**state,'deployment_queue_length':len(queue['items']),'status':'synchronized'}
        write_json(self.home/'.companyos_runtime'/'venture_builder_live.json',live)
        append_jsonl(self.home/'.companyos_runtime'/'full_autonomy_journal.jsonl',{'ts':now(),'event':'venture_build_ready_for_review' if passed else 'venture_build_validation_failed','event_type':'venture_build_ready_for_review' if passed else 'venture_build_validation_failed','orchestration_id':execution_id,'state':live})
        return {'status':'ready_for_review' if passed else 'validation_failed','builder':live,'tests':{'stdout':cp.stdout[-4000:],'stderr':cp.stderr[-4000:]}}
