#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail

ROOT="${COMPANYOS_HOME:-$HOME/companyos}"
STAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP="$ROOT/.companyos_backups/candidate_intelligence_v2_$STAMP"
PATCH_TMP="$PREFIX/tmp/companyos_candidate_intelligence_v2_$STAMP.py"

cd "$ROOT"
source "$HOME/.companyos_launch_env" 2>/dev/null || true

mkdir -p "$BACKUP"
cp -a companyos/runtime/profit_opportunity_engine.py "$BACKUP/" 2>/dev/null || true

echo "============================================================"
echo " CompanyOS Candidate Intelligence + Qualification Fix V2"
echo "============================================================"

printf '%s' "ZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCnA9UGF0aC5ob21lKCkvImNvbXBhbnlvcyIvImNvbXBhbnlvcy9ydW50aW1lL3Byb2ZpdF9vcHBvcnR1bml0eV9lbmdpbmUucHkiCnM9cC5yZWFkX3RleHQoKQptYXJrZXI9IiMgQ09NUEFOWU9TX0NBTkRJREFURV9JTlRFTExJR0VOQ0VfVjIiCmFwcGVuZF9jb2RlPSdcbiMgQ09NUEFOWU9TX0NBTkRJREFURV9JTlRFTExJR0VOQ0VfVjJcblxuX0NJX0lOVEVSTkFMX01BUktFUlMgPSAoXG4gICAgImNvbXBhbnlvcyBvcHBvcnR1bml0eSBlbmdpbmUgdGVzdCIsXG4gICAgInJlc2VhcmNoIG1hcmtldHMgYmVmb3JlIGJ1aWxkaW5nIixcbiAgICAicmVzZWFyY2gvYW5hbHlzaXMgb25seSIsXG4gICAgInByZXNlcnZlIGFsbCBleHRlcm5hbCIsXG4gICAgIm1hcmsgZXN0aW1hdGVzIGhvbmVzdGx5IixcbiAgICAiZGlzY292ZXIgYXQgbGVhc3QiLFxuICAgICJtYXRlcmlhbGx5IGRpZmZlcmVudCBvcHBvcnR1bml0aWVzIixcbiAgICAicGVyc2lzdCBhIG1hcmtldC1zY2FuIixcbiAgICAicGVyc2lzdCBhIG1hcmtldCBzY2FuIixcbiAgICAiZG8gbm90IGdlbmVyYXRlIHN1cGVyZmljaWFsIixcbiAgICAiZG8gbm90IGR1cGxpY2F0ZSIsXG4gICAgImNvbnN0cnVjdGlvbiBhbmQgc2VydmljZSBidXNpbmVzc2VzIG1heSBhcHBlYXIiLFxuICAgICJwcmVmZXIgY29tbWVyY2lhbGx5IGRpc3RpbmN0IG9wcG9ydHVuaXRpZXMiLFxuICAgICJmb3IgZWFjaCBjYW5kaWRhdGUiLFxuICAgICJlYWNoIHJlY29yZCBtdXN0IixcbiAgICAiZ2VuZXJhdGUgYXQgbGVhc3QiLFxuICAgICJ1c2UgMC0xMDAgbnVtZXJpYyBzY29yZXMiLFxuICAgICJ0aGlzIHN0YWdlIGlzIHJlc2VhcmNoIixcbilcblxuZGVmIF9jaV90ZXh0X2Zyb21fb3Bwb3J0dW5pdHkobyk6XG4gICAgcGFydHMgPSBbXG4gICAgICAgIHN0cihnZXRhdHRyKG8sICJuYW1lIiwgIiIpIG9yICIiKSxcbiAgICAgICAgc3RyKGdldGF0dHIobywgInNvdXJjZSIsICIiKSBvciAiIiksXG4gICAgICAgIHN0cihnZXRhdHRyKG8sICJuZXh0X2FjdGlvbiIsICIiKSBvciAiIiksXG4gICAgXVxuICAgIHBheWxvYWQgPSBnZXRhdHRyKG8sICJwYXlsb2FkIiwge30pIG9yIHt9XG4gICAgdHJ5OlxuICAgICAgICBwYXJ0cy5hcHBlbmQoanNvbi5kdW1wcyhwYXlsb2FkLCBzb3J0X2tleXM9VHJ1ZSwgZGVmYXVsdD1zdHIpKVxuICAgIGV4Y2VwdCBFeGNlcHRpb246XG4gICAgICAgIHBhcnRzLmFwcGVuZChzdHIocGF5bG9hZCkpXG4gICAgcmV0dXJuICIgIi5qb2luKHBhcnRzKS5sb3dlcigpXG5cbmRlZiBjYW5kaWRhdGVfaXNfaW50ZXJuYWxfaW5zdHJ1Y3Rpb24obyk6XG4gICAgdCA9IF9jaV90ZXh0X2Zyb21fb3Bwb3J0dW5pdHkobylcbiAgICBzb3VyY2UgPSBzdHIoZ2V0YXR0cihvLCAic291cmNlIiwgIiIpIG9yICIiKS5sb3dlcigpXG4gICAgbmFtZSA9IHN0cihnZXRhdHRyKG8sICJuYW1lIiwgIiIpIG9yICIiKS5sb3dlcigpXG4gICAgaWYgYW55KHggaW4gdCBmb3IgeCBpbiBfQ0lfSU5URVJOQUxfTUFSS0VSUyk6XG4gICAgICAgIHJldHVybiBUcnVlXG4gICAgaWYgIi90ZXN0cy8iIGluIHNvdXJjZSBvciBzb3VyY2Uuc3RhcnRzd2l0aCgidGVzdHMvIik6XG4gICAgICAgIHJldHVybiBUcnVlXG4gICAgaWYgInRlc3QiIGluIG5hbWUgYW5kICJvcHBvcnR1bml0eSIgaW4gbmFtZTpcbiAgICAgICAgcmV0dXJuIFRydWVcbiAgICBpbXBlcmF0aXZlX2hpdHMgPSBzdW0oXG4gICAgICAgIDEgZm9yIHggaW4gKFxuICAgICAgICAgICAgIm11c3QgIiwgImRvIG5vdCAiLCAicHJlc2VydmUgIiwgImdlbmVyYXRlIGF0IGxlYXN0IixcbiAgICAgICAgICAgICJmb3IgZWFjaCBjYW5kaWRhdGUiLCAicmVzZWFyY2ggbWFya2V0cyIsICJ1c2UgMC0xMDAiXG4gICAgICAgICkgaWYgeCBpbiB0XG4gICAgKVxuICAgIGlmIGltcGVyYXRpdmVfaGl0cyA+PSAyIGFuZCBub3QgZ2V0YXR0cihvLCAibmV4dF9hY3Rpb24iLCAiIik6XG4gICAgICAgIHJldHVybiBUcnVlXG4gICAgcmV0dXJuIEZhbHNlXG5cbl9jYW5kaWRhdGVfaW50ZWxfbGVnYWN5X2Rpc2NvdmVyID0gZGlzY292ZXJcblxuZGVmIGRpc2NvdmVyKCk6XG4gICAgcm93cyA9IF9jYW5kaWRhdGVfaW50ZWxfbGVnYWN5X2Rpc2NvdmVyKClcbiAgICBjb21tZXJjaWFsID0gW28gZm9yIG8gaW4gcm93cyBpZiBub3QgY2FuZGlkYXRlX2lzX2ludGVybmFsX2luc3RydWN0aW9uKG8pXVxuICAgIGV2ZW50KFxuICAgICAgICAiQ0FORElEQVRFX0lOVEVMTElHRU5DRV9GSUxURVIiLFxuICAgICAgICBpbnB1dF9jb3VudD1sZW4ocm93cyksXG4gICAgICAgIGNvbW1lcmNpYWxfY291bnQ9bGVuKGNvbW1lcmNpYWwpLFxuICAgICAgICByZWplY3RlZF9pbnRlcm5hbF9jb3VudD1sZW4ocm93cyktbGVuKGNvbW1lcmNpYWwpLFxuICAgIClcbiAgICByZXR1cm4gY29tbWVyY2lhbFxuXG5kZWYgX2NhbmRpZGF0ZV9xdWFsaWZpY2F0aW9uX3JlYXNvbnMobyk6XG4gICAgcmVhc29ucyA9IFtdXG4gICAgbWluX3Njb3JlID0gbnVtKG9zLmdldGVudigiQ09NUEFOWU9TX1BST0ZJVF9NSU5fU0NPUkUiLCAiNDUiKSlcbiAgICBpZiBvLnNjb3JlIDwgbWluX3Njb3JlOlxuICAgICAgICByZWFzb25zLmFwcGVuZCgic2NvcmVfYmVsb3dfZXhlY3V0aW9uX3RocmVzaG9sZCIpXG4gICAgaWYgby5ldmlkZW5jZV9jb3VudCA8IDE6XG4gICAgICAgIHJlYXNvbnMuYXBwZW5kKCJtaXNzaW5nX2V4dGVybmFsX2V2aWRlbmNlIilcbiAgICBpZiBvLnByb2JhYmlsaXR5IDw9IDA6XG4gICAgICAgIHJlYXNvbnMuYXBwZW5kKCJwcm9iYWJpbGl0eV91bmVzdGltYXRlZCIpXG4gICAgaWYgby5leHBlY3RlZF9wcm9maXQgPD0gMDpcbiAgICAgICAgcmVhc29ucy5hcHBlbmQoInByb2ZpdF91bmVzdGltYXRlZCIpXG4gICAgaWYgby5yZWFkaW5lc3MgPD0gMDpcbiAgICAgICAgcmVhc29ucy5hcHBlbmQoInJlYWRpbmVzc191bmVzdGltYXRlZCIpXG4gICAgaWYgbm90IHN0cihvLm5leHRfYWN0aW9uIG9yICIiKS5zdHJpcCgpOlxuICAgICAgICByZWFzb25zLmFwcGVuZCgibWlzc2luZ19leGVjdXRhYmxlX25leHRfYWN0aW9uIilcbiAgICBpZiBvLmNvbXBsaWFuY2VfcmlzayA+PSA4MDpcbiAgICAgICAgcmVhc29ucy5hcHBlbmQoImNvbXBsaWFuY2Vfcmlza190b29faGlnaCIpXG4gICAgcmV0dXJuIHJlYXNvbnNcblxuZGVmIF93cml0ZV9jYW5kaWRhdGVfZW5yaWNobWVudF9xdWV1ZShyb3dzKTpcbiAgICBxdWV1ZSA9IFtdXG4gICAgZm9yIG8gaW4gcm93c1s6MzBdOlxuICAgICAgICByZWFzb25zID0gX2NhbmRpZGF0ZV9xdWFsaWZpY2F0aW9uX3JlYXNvbnMobylcbiAgICAgICAgaWYgbm90IHJlYXNvbnM6XG4gICAgICAgICAgICBjb250aW51ZVxuICAgICAgICBxdWV1ZS5hcHBlbmQoe1xuICAgICAgICAgICAgImlkIjogby5pZCxcbiAgICAgICAgICAgICJuYW1lIjogby5uYW1lLFxuICAgICAgICAgICAgInNvdXJjZSI6IG8uc291cmNlLFxuICAgICAgICAgICAgInNjb3JlIjogby5zY29yZSxcbiAgICAgICAgICAgICJtaXNzaW5nX29yX2Jsb2NraW5nIjogcmVhc29ucyxcbiAgICAgICAgICAgICJjdXJyZW50Ijoge1xuICAgICAgICAgICAgICAgICJleHBlY3RlZF9wcm9maXQiOiBvLmV4cGVjdGVkX3Byb2ZpdCxcbiAgICAgICAgICAgICAgICAicHJvYmFiaWxpdHkiOiBvLnByb2JhYmlsaXR5LFxuICAgICAgICAgICAgICAgICJldmlkZW5jZV9jb3VudCI6IG8uZXZpZGVuY2VfY291bnQsXG4gICAgICAgICAgICAgICAgImV2aWRlbmNlX3F1YWxpdHkiOiBvLmV2aWRlbmNlX3F1YWxpdHksXG4gICAgICAgICAgICAgICAgInJlYWRpbmVzcyI6IG8ucmVhZGluZXNzLFxuICAgICAgICAgICAgICAgICJ0aW1lX3RvX2Nhc2hfZGF5cyI6IG8udGltZV90b19jYXNoX2RheXMsXG4gICAgICAgICAgICAgICAgImNhcGl0YWxfcmVxdWlyZWQiOiBvLmNhcGl0YWxfcmVxdWlyZWQsXG4gICAgICAgICAgICAgICAgIm5leHRfYWN0aW9uIjogby5uZXh0X2FjdGlvbixcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAicmVzZWFyY2hfY29udHJhY3QiOiAoXG4gICAgICAgICAgICAgICAgIlJlc2VhcmNoIG9ubHkgdGhpcyBjb21tZXJjaWFsIG9wcG9ydHVuaXR5LiBSZXNvbHZlIHRoZSBsaXN0ZWQgZ2FwcyAiXG4gICAgICAgICAgICAgICAgIndpdGggcmVhbCBldmlkZW5jZS4gRG8gbm90IGludmVudCBwcm9iYWJpbGl0eSwgcHJvZml0LCByZWFkaW5lc3MsICJcbiAgICAgICAgICAgICAgICAiY3VzdG9tZXJzLCBvciBldmlkZW5jZS4gUmV0dXJuIGV2aWRlbmNlIHNvdXJjZXMgYW5kIG9uZSBleGVjdXRhYmxlIG5leHQgYWN0aW9uLiJcbiAgICAgICAgICAgICksXG4gICAgICAgIH0pXG4gICAgd3JpdGUoUlQgLyAicHJvZml0X2NhbmRpZGF0ZV9lbnJpY2htZW50X3F1ZXVlLmpzb24iLCB7XG4gICAgICAgICJ0cyI6IHRpbWUudGltZSgpLFxuICAgICAgICAiY291bnQiOiBsZW4ocXVldWUpLFxuICAgICAgICAiY2FuZGlkYXRlcyI6IHF1ZXVlLFxuICAgIH0pXG4gICAgcmV0dXJuIHF1ZXVlXG5cbmRlZiBjaG9vc2UoKTpcbiAgICByb3dzID0gZGlzY292ZXIoKVxuICAgIGVsaWdpYmxlID0gW11cbiAgICByZWplY3RlZCA9IFtdXG4gICAgZm9yIG8gaW4gcm93czpcbiAgICAgICAgcmVhc29ucyA9IF9jYW5kaWRhdGVfcXVhbGlmaWNhdGlvbl9yZWFzb25zKG8pXG4gICAgICAgIGlmIHJlYXNvbnM6XG4gICAgICAgICAgICByZWplY3RlZC5hcHBlbmQoe1xuICAgICAgICAgICAgICAgICJpZCI6IG8uaWQsXG4gICAgICAgICAgICAgICAgIm5hbWUiOiBvLm5hbWUsXG4gICAgICAgICAgICAgICAgInNvdXJjZSI6IG8uc291cmNlLFxuICAgICAgICAgICAgICAgICJzY29yZSI6IG8uc2NvcmUsXG4gICAgICAgICAgICAgICAgInJlYXNvbnMiOiByZWFzb25zLFxuICAgICAgICAgICAgfSlcbiAgICAgICAgZWxzZTpcbiAgICAgICAgICAgIGVsaWdpYmxlLmFwcGVuZChvKVxuICAgIGNob3NlbiA9IGVsaWdpYmxlWzBdIGlmIGVsaWdpYmxlIGVsc2UgTm9uZVxuICAgIHF1ZXVlID0gX3dyaXRlX2NhbmRpZGF0ZV9lbnJpY2htZW50X3F1ZXVlKHJvd3MpXG4gICAgeCA9IHtcbiAgICAgICAgInRzIjogdGltZS50aW1lKCksXG4gICAgICAgICJvYmplY3RpdmUiOiAicmlza19hZGp1c3RlZF9yZWFsaXplZF9wcm9maXQiLFxuICAgICAgICAiY2FuZGlkYXRlX2NvdW50IjogbGVuKHJvd3MpLFxuICAgICAgICAiZWxpZ2libGVfY291bnQiOiBsZW4oZWxpZ2libGUpLFxuICAgICAgICAicmVqZWN0ZWRfY291bnQiOiBsZW4ocmVqZWN0ZWQpLFxuICAgICAgICAiZGVjaXNpb24iOiAiZXhlY3V0ZV9jYW5kaWRhdGUiIGlmIGNob3NlbiBlbHNlICJyZXNlYXJjaF9tb3JlIixcbiAgICAgICAgImNob3NlbiI6IGFzZGljdChjaG9zZW4pIGlmIGNob3NlbiBlbHNlIE5vbmUsXG4gICAgICAgICJyYW5rZWQiOiBbYXNkaWN0KG8pIGZvciBvIGluIHJvd3NbOjMwXV0sXG4gICAgICAgICJxdWFsaWZpY2F0aW9uX3JlamVjdGlvbnMiOiByZWplY3RlZFs6MzBdLFxuICAgICAgICAiZW5yaWNobWVudF9xdWV1ZV9jb3VudCI6IGxlbihxdWV1ZSksXG4gICAgfVxuICAgIHdyaXRlKFNUQVRVUywgeClcbiAgICBldmVudChcbiAgICAgICAgIkRFQ0lTSU9OIixcbiAgICAgICAgZGVjaXNpb249eFsiZGVjaXNpb24iXSxcbiAgICAgICAgY2FuZGlkYXRlX2NvdW50PWxlbihyb3dzKSxcbiAgICAgICAgZWxpZ2libGVfY291bnQ9bGVuKGVsaWdpYmxlKSxcbiAgICAgICAgZW5yaWNobWVudF9xdWV1ZV9jb3VudD1sZW4ocXVldWUpLFxuICAgIClcbiAgICByZXR1cm4geFxuJwppZiBtYXJrZXIgbm90IGluIHM6CiAgICBwLndyaXRlX3RleHQocysnXG4nK2FwcGVuZF9jb2RlKQogICAgcHJpbnQoJ0VOR0lORV9DQU5ESURBVEVfSU5URUxMSUdFTkNFX1YyPUlOU1RBTExFRCcpCmVsc2U6CiAgICBwcmludCgnRU5HSU5FX0NBTkRJREFURV9JTlRFTExJR0VOQ0VfVjI9QUxSRUFEWV9JTlNUQUxMRUQnKQo=" | base64 -d > "$PATCH_TMP"
python "$PATCH_TMP"
rm -f "$PATCH_TMP"

echo "[1/6] Syntax..."
python -m py_compile companyos/runtime/profit_opportunity_engine.py

echo "[2/6] Intelligence smoke tests..."
python - <<'PY'
from companyos.runtime.profit_opportunity_engine import Opportunity, candidate_is_internal_instruction, _candidate_qualification_reasons
bad=Opportunity(id="x",name="Research markets before building.",source="tests/x.json",next_action="",expected_profit=50,probability=0,readiness=50)
assert candidate_is_internal_instruction(bad)
good=Opportunity(id="y",name="Commercial lead qualification service",source="workspace/y.json",next_action="Contact 10 qualified buyers with a priced offer",expected_profit=2500,probability=55,evidence_count=2,evidence_quality=60,readiness=70,compliance_risk=10)
good.score=68
assert not candidate_is_internal_instruction(good)
assert _candidate_qualification_reasons(good)==[]
print("CANDIDATE_INTELLIGENCE_TESTS=PASS")
PY

echo "[3/6] Live candidate report..."
python - <<'PY'
import json
from companyos.runtime.profit_opportunity_engine import choose
x=choose()
print(json.dumps({
 "candidate_count":x.get("candidate_count"),
 "eligible_count":x.get("eligible_count"),
 "rejected_count":x.get("rejected_count"),
 "decision":x.get("decision"),
 "enrichment_queue_count":x.get("enrichment_queue_count"),
 "top_names":[r.get("name") for r in x.get("ranked",[])[:8]],
 "top_rejections":x.get("qualification_rejections",[])[:8],
},indent=2,default=str))
PY

echo "[4/6] Commit/push..."
git add -- companyos/runtime/profit_opportunity_engine.py
git diff --cached --quiet || git commit -m "Filter noncommercial profit candidates and expose enrichment gaps"
BRANCH="$(git branch --show-current)"
[ -n "$BRANCH" ] && git push origin "$BRANCH" || true

echo "[5/6] Restart..."
scripts/companyosctl restart || true
sleep 8

echo "[6/6] Current state..."
python - <<'PY'
import json
from pathlib import Path
from companyos.runtime.profit_opportunity_engine import choose
x=choose()
print("candidate_count =",x.get("candidate_count"))
print("eligible_count =",x.get("eligible_count"))
print("decision =",x.get("decision"))
p=Path.home()/"companyos"/".companyos_runtime"/"profit_candidate_enrichment_queue.json"
if p.exists():
 d=json.loads(p.read_text())
 print("enrichment_queue_count =",d.get("count"))
 for i,row in enumerate(d.get("candidates",[])[:10],1):
  print(i,row.get("name"),"->",", ".join(row.get("missing_or_blocking",[])))
PY

echo
scripts/companyosctl status || true
echo
echo "Backup: $BACKUP"
echo "COMPANYOS_CANDIDATE_INTELLIGENCE_QUALIFICATION_FIX_V2=PASS"
