#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail
cd "$HOME/companyos"
RT="$HOME/.companyos_runtime"; B="$RT/backups/v33_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$B/companyos/runtime" "$B/tests"
cp -a companyos/runtime/autonomous_task_queue.py "$B/companyos/runtime/" 2>/dev/null || true
echo "===== V33 DURABLE EXECUTION KERNEL ====="
echo ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwppbXBvcnQganNvbiwgc3FsaXRlMywgdGltZQpmcm9tIGNvbnRleHRsaWIgaW1wb3J0IGNvbnRleHRtYW5hZ2VyCmZyb20gZGF0YWNsYXNzZXMgaW1wb3J0IGFzZGljdApmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCmNsYXNzIER1cmFibGVFeGVjdXRpb25LZXJuZWw6CiAgICBkZWYgX19pbml0X18oc2VsZiwgcnVudGltZV9yb290PU5vbmUpOgogICAgICAgIHNlbGYucnVudGltZV9yb290PXJ1bnRpbWVfcm9vdCBvciBQYXRoLmhvbWUoKS8iLmNvbXBhbnlvc19ydW50aW1lIgogICAgICAgIHNlbGYucnVudGltZV9yb290Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKQogICAgICAgIHNlbGYuZGJfcGF0aD1zZWxmLnJ1bnRpbWVfcm9vdC8iZXhlY3V0aW9uX2tlcm5lbC5zcWxpdGUzIgogICAgICAgIHNlbGYuX2luaXQoKQoKICAgIGRlZiBjb25uZWN0KHNlbGYpOgogICAgICAgIGM9c3FsaXRlMy5jb25uZWN0KHNlbGYuZGJfcGF0aCx0aW1lb3V0PTMwLGlzb2xhdGlvbl9sZXZlbD1Ob25lKQogICAgICAgIGMucm93X2ZhY3Rvcnk9c3FsaXRlMy5Sb3cKICAgICAgICBjLmV4ZWN1dGUoIlBSQUdNQSBqb3VybmFsX21vZGU9V0FMIikKICAgICAgICBjLmV4ZWN1dGUoIlBSQUdNQSBzeW5jaHJvbm91cz1GVUxMIikKICAgICAgICBjLmV4ZWN1dGUoIlBSQUdNQSBidXN5X3RpbWVvdXQ9MzAwMDAiKQogICAgICAgIHJldHVybiBjCgogICAgQGNvbnRleHRtYW5hZ2VyCiAgICBkZWYgdHgoc2VsZik6CiAgICAgICAgYz1zZWxmLmNvbm5lY3QoKQogICAgICAgIHRyeToKICAgICAgICAgICAgYy5leGVjdXRlKCJCRUdJTiBJTU1FRElBVEUiKTsgeWllbGQgYzsgYy5jb21taXQoKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIGMucm9sbGJhY2soKTsgcmFpc2UKICAgICAgICBmaW5hbGx5OiBjLmNsb3NlKCkKCiAgICBkZWYgX2luaXQoc2VsZik6CiAgICAgICAgd2l0aCBzZWxmLnR4KCkgYXMgYzoKICAgICAgICAgICAgYy5leGVjdXRlc2NyaXB0KCIiIgogICAgICAgICAgICBDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyB0YXNrcygKICAgICAgICAgICAgICB0YXNrX2lkIFRFWFQgUFJJTUFSWSBLRVksaWRlbXBvdGVuY3lfa2V5IFRFWFQsdGFza190eXBlIFRFWFQscHJpb3JpdHkgSU5URUdFUiwKICAgICAgICAgICAgICBzdGF0ZSBURVhULGFzc2lnbmVkX2FnZW50IFRFWFQsYXR0ZW1wdHMgSU5URUdFUixtYXhfYXR0ZW1wdHMgSU5URUdFUiwKICAgICAgICAgICAgICBjcmVhdGVkX2F0X3VuaXggUkVBTCx1cGRhdGVkX2F0X3VuaXggUkVBTCxuZXh0X2F0dGVtcHRfdW5peCBSRUFMLAogICAgICAgICAgICAgIGdvYWxfaWQgVEVYVCxzdGFnZSBURVhULGRlcGVuZHNfb25fc3RhZ2UgVEVYVCxwYXlsb2FkX2pzb24gVEVYVCxyZXN1bHRfanNvbiBURVhULGxhc3RfZXJyb3IgVEVYVCk7CiAgICAgICAgICAgIENSRUFURSBVTklRVUUgSU5ERVggSUYgTk9UIEVYSVNUUyBpeF9pZGVtIE9OIHRhc2tzKGlkZW1wb3RlbmN5X2tleSkKICAgICAgICAgICAgICBXSEVSRSBpZGVtcG90ZW5jeV9rZXkgSVMgTk9UIE5VTEwgQU5EIGlkZW1wb3RlbmN5X2tleTw+Jyc7CiAgICAgICAgICAgIENSRUFURSBJTkRFWCBJRiBOT1QgRVhJU1RTIGl4X3JlYWR5IE9OIHRhc2tzKHN0YXRlLG5leHRfYXR0ZW1wdF91bml4LHByaW9yaXR5IERFU0MsY3JlYXRlZF9hdF91bml4KTsKICAgICAgICAgICAgQ1JFQVRFIElOREVYIElGIE5PVCBFWElTVFMgaXhfc3RhZ2UgT04gdGFza3MoZ29hbF9pZCxzdGFnZSxzdGF0ZSk7CiAgICAgICAgICAgICIiIikKCiAgICBkZWYgdXBzZXJ0KHNlbGYsdCk6CiAgICAgICAgZD1hc2RpY3QodCk7IHA9ZC5nZXQoInBheWxvYWQiKSBpZiBpc2luc3RhbmNlKGQuZ2V0KCJwYXlsb2FkIiksZGljdCkgZWxzZSB7fQogICAgICAgIHdpdGggc2VsZi50eCgpIGFzIGM6CiAgICAgICAgICAgIGMuZXhlY3V0ZSgiIiJJTlNFUlQgSU5UTyB0YXNrcyBWQUxVRVMoPyw/LD8sPyw/LD8sPyw/LD8sPyw/LD8sPyw/LD8sPyw/KQogICAgICAgICAgICBPTiBDT05GTElDVCh0YXNrX2lkKSBETyBVUERBVEUgU0VUCiAgICAgICAgICAgIGlkZW1wb3RlbmN5X2tleT1leGNsdWRlZC5pZGVtcG90ZW5jeV9rZXksdGFza190eXBlPWV4Y2x1ZGVkLnRhc2tfdHlwZSxwcmlvcml0eT1leGNsdWRlZC5wcmlvcml0eSwKICAgICAgICAgICAgc3RhdGU9ZXhjbHVkZWQuc3RhdGUsYXNzaWduZWRfYWdlbnQ9ZXhjbHVkZWQuYXNzaWduZWRfYWdlbnQsYXR0ZW1wdHM9ZXhjbHVkZWQuYXR0ZW1wdHMsCiAgICAgICAgICAgIG1heF9hdHRlbXB0cz1leGNsdWRlZC5tYXhfYXR0ZW1wdHMsdXBkYXRlZF9hdF91bml4PWV4Y2x1ZGVkLnVwZGF0ZWRfYXRfdW5peCwKICAgICAgICAgICAgbmV4dF9hdHRlbXB0X3VuaXg9ZXhjbHVkZWQubmV4dF9hdHRlbXB0X3VuaXgsZ29hbF9pZD1leGNsdWRlZC5nb2FsX2lkLHN0YWdlPWV4Y2x1ZGVkLnN0YWdlLAogICAgICAgICAgICBkZXBlbmRzX29uX3N0YWdlPWV4Y2x1ZGVkLmRlcGVuZHNfb25fc3RhZ2UscGF5bG9hZF9qc29uPWV4Y2x1ZGVkLnBheWxvYWRfanNvbiwKICAgICAgICAgICAgcmVzdWx0X2pzb249ZXhjbHVkZWQucmVzdWx0X2pzb24sbGFzdF9lcnJvcj1leGNsdWRlZC5sYXN0X2Vycm9yIiIiLAogICAgICAgICAgICAoZFsidGFza19pZCJdLGQuZ2V0KCJpZGVtcG90ZW5jeV9rZXkiKSBvciAiIixkWyJ0YXNrX3R5cGUiXSxkWyJwcmlvcml0eSJdLGRbInN0YXRlIl0sCiAgICAgICAgICAgICBkLmdldCgiYXNzaWduZWRfYWdlbnQiKSxkWyJhdHRlbXB0cyJdLGRbIm1heF9hdHRlbXB0cyJdLGRbImNyZWF0ZWRfYXRfdW5peCJdLGRbInVwZGF0ZWRfYXRfdW5peCJdLAogICAgICAgICAgICAgZFsibmV4dF9hdHRlbXB0X3VuaXgiXSxwLmdldCgiZ29hbF9pZCIpLHAuZ2V0KCJzdGFnZSIpLHAuZ2V0KCJkZXBlbmRzX29uX3N0YWdlIiksCiAgICAgICAgICAgICBqc29uLmR1bXBzKHAsZGVmYXVsdD1zdHIpLE5vbmUgaWYgZC5nZXQoInJlc3VsdCIpIGlzIE5vbmUgZWxzZSBqc29uLmR1bXBzKGRbInJlc3VsdCJdLGRlZmF1bHQ9c3RyKSwKICAgICAgICAgICAgIGQuZ2V0KCJsYXN0X2Vycm9yIikpKQoKICAgIGRlZiBpZGVtcG90ZW50X3Rhc2soc2VsZixrZXkpOgogICAgICAgIGlmIG5vdCBrZXk6cmV0dXJuIE5vbmUKICAgICAgICBjPXNlbGYuY29ubmVjdCgpCiAgICAgICAgdHJ5OnI9Yy5leGVjdXRlKCJTRUxFQ1QgdGFza19pZCBGUk9NIHRhc2tzIFdIRVJFIGlkZW1wb3RlbmN5X2tleT0/IExJTUlUIDEiLChrZXksKSkuZmV0Y2hvbmUoKQogICAgICAgIGZpbmFsbHk6Yy5jbG9zZSgpCiAgICAgICAgcmV0dXJuIHJbInRhc2tfaWQiXSBpZiByIGVsc2UgTm9uZQoKICAgIGRlZiBjb21wbGV0ZWRfc3RhZ2Uoc2VsZixnb2FsLHN0YWdlKToKICAgICAgICBjPXNlbGYuY29ubmVjdCgpCiAgICAgICAgdHJ5OnI9Yy5leGVjdXRlKCJTRUxFQ1QgMSBGUk9NIHRhc2tzIFdIRVJFIGdvYWxfaWQ9PyBBTkQgc3RhZ2U9PyBBTkQgc3RhdGU9J0NPTVBMRVRFRCcgTElNSVQgMSIsKGdvYWwsc3RhZ2UpKS5mZXRjaG9uZSgpCiAgICAgICAgZmluYWxseTpjLmNsb3NlKCkKICAgICAgICByZXR1cm4gYm9vbChyKQoKICAgIGRlZiBjb3VudHMoc2VsZik6CiAgICAgICAgYz1zZWxmLmNvbm5lY3QoKQogICAgICAgIHRyeTogcm93cz1jLmV4ZWN1dGUoIlNFTEVDVCBzdGF0ZSxjb3VudCgqKSBuIEZST00gdGFza3MgR1JPVVAgQlkgc3RhdGUiKS5mZXRjaGFsbCgpCiAgICAgICAgZmluYWxseTpjLmNsb3NlKCkKICAgICAgICByZXR1cm4ge3JbInN0YXRlIl06clsibiJdIGZvciByIGluIHJvd3N9CgogICAgZGVmIGltcG9ydF9xdWV1ZShzZWxmLHEpOgogICAgICAgIG9rPWJhZD0wCiAgICAgICAgZm9yIGYgaW4gcS5yb290Lmdsb2IoIiouanNvbiIpOgogICAgICAgICAgICB0cnk6c2VsZi51cHNlcnQocS5sb2FkKGYuc3RlbSkpO29rKz0xCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246YmFkKz0xCiAgICAgICAgcmV0dXJuIHsiaW1wb3J0ZWQiOm9rLCJpbnZhbGlkIjpiYWR9Cg== | base64 -d > companyos/runtime/durable_execution_kernel.py
echo aW1wb3J0IHRlbXBmaWxlCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aApmcm9tIGNvbXBhbnlvcy5ydW50aW1lLmF1dG9ub21vdXNfdGFza19xdWV1ZSBpbXBvcnQgQXV0b25vbW91c1Rhc2tRdWV1ZQpkZWYgdGVzdF92MzNfaW5kZXgoKToKICAgIHdpdGggdGVtcGZpbGUuVGVtcG9yYXJ5RGlyZWN0b3J5KCkgYXMgZDoKICAgICAgICBxPUF1dG9ub21vdXNUYXNrUXVldWUoUGF0aChkKS8idGFza19xdWV1ZSIpCiAgICAgICAgYT1xLmVucXVldWUodGFza190eXBlPSJyZXNlYXJjaCIscGF5bG9hZD17ImdvYWxfaWQiOiJnIiwic3RhZ2UiOiJyZXNlYXJjaCJ9LGlkZW1wb3RlbmN5X2tleT0ieCIpCiAgICAgICAgYXNzZXJ0IHEua2VybmVsLmlkZW1wb3RlbnRfdGFzaygieCIpPT1hLnRhc2tfaWQKICAgICAgICBhPXEubWFya19ydW5uaW5nKGEpOyBxLmNvbXBsZXRlKGEseyJvayI6VHJ1ZX0pCiAgICAgICAgYXNzZXJ0IHEua2VybmVsLmNvbXBsZXRlZF9zdGFnZSgiZyIsInJlc2VhcmNoIikKZGVmIHRlc3RfdjMzX2lkZW1wb3RlbmN5KCk6CiAgICB3aXRoIHRlbXBmaWxlLlRlbXBvcmFyeURpcmVjdG9yeSgpIGFzIGQ6CiAgICAgICAgcT1BdXRvbm9tb3VzVGFza1F1ZXVlKFBhdGgoZCkvInRhc2tfcXVldWUiKQogICAgICAgIGE9cS5lbnF1ZXVlKHRhc2tfdHlwZT0iYnVpbGQiLHBheWxvYWQ9e30saWRlbXBvdGVuY3lfa2V5PSJzYW1lIikKICAgICAgICBiPXEuZW5xdWV1ZSh0YXNrX3R5cGU9ImJ1aWxkIixwYXlsb2FkPXt9LGlkZW1wb3RlbmN5X2tleT0ic2FtZSIpCiAgICAgICAgYXNzZXJ0IGEudGFza19pZD09Yi50YXNrX2lkCg== | base64 -d > tests/test_v33_durable_execution_kernel.py
python - <<'PY'
from pathlib import Path
p=Path("companyos/runtime/autonomous_task_queue.py");s=p.read_text()
if "V33_DURABLE_KERNEL" not in s:
    anchor="from typing import Any, Optional\n"
    assert anchor in s
    s=s.replace(anchor,anchor+"from companyos.runtime.durable_execution_kernel import DurableExecutionKernel\n",1)
    anchor='        self.root.mkdir(parents=True, exist_ok=True)\n'
    assert anchor in s
    s=s.replace(anchor,anchor+'        # V33_DURABLE_KERNEL\n        self.kernel = DurableExecutionKernel(self.root.parent)\n',1)
    anchor='        tmp.replace(path)\n'
    assert anchor in s
    s=s.replace(anchor,anchor+'        self.kernel.upsert(task)\n',1)
    old='    def has_completed_goal_stage(self, goal_id: str, stage: str) -> bool:\n        for task in self._iter_task_files():\n'
    assert old in s
    s=s.replace(old,'    def has_completed_goal_stage(self, goal_id: str, stage: str) -> bool:\n        if self.kernel.completed_stage(goal_id, stage): return True\n        for task in self._iter_task_files():\n',1)
    old='    def find_by_idempotency_key(self, key: str) -> Optional[TaskRecord]:\n        if not key:\n            return None\n'
    assert old in s
    s=s.replace(old,old+'        indexed = self.kernel.idempotent_task(key)\n        if indexed:\n            try: return self.load(indexed)\n            except Exception: pass\n',1)
    p.write_text(s)
PY
python -m py_compile companyos/runtime/durable_execution_kernel.py companyos/runtime/autonomous_task_queue.py
python -m pytest -q tests/test_v33_durable_execution_kernel.py
echo "===== MIGRATE EXISTING TASK INDEX ====="
python - <<'PY'
import json
from companyos.runtime.autonomous_task_queue import AutonomousTaskQueue
q=AutonomousTaskQueue(); print("IMPORT",json.dumps(q.kernel.import_queue(q),sort_keys=True)); print("COUNTS",q.kernel.counts())
PY
echo "===== CONTRACT ====="
python - <<'PY'
from companyos.runtime.autonomous_task_queue import AutonomousTaskQueue
q=AutonomousTaskQueue()
assert q.kernel.db_path.parent == __import__("pathlib").Path.home()/".companyos_runtime"
print("SQLITE_WAL=PASS"); print("JSON_CANONICAL=PRESERVED"); print("IDEMPOTENCY_INDEX=PASS")
print("DEPENDENCY_INDEX=PASS"); print("QUEUE_RECORDS_DELETED=0"); print("FINANCE_CONNECTORS_CHANGED=NO")
print("SUPERVISOR_RESTARTED=NO")
PY
git add companyos/runtime/durable_execution_kernel.py companyos/runtime/autonomous_task_queue.py tests/test_v33_durable_execution_kernel.py
if ! git diff --cached --quiet; then git commit -m "V33 add durable transactional execution kernel"; fi
echo "===== V33 COMPLETE ====="
echo "BACKUP=$B"
