#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail
cd "$HOME/companyos"
source "$HOME/.companyos_launch_env" 2>/dev/null || true

STAMP="$(date +%Y%m%d_%H%M%S)"
BK="$HOME/companyos/.companyos_backups/capability_expansion_v4_$STAMP"
mkdir -p "$BK"
cp -a companyos/runtime/capability_expansion.py "$BK/"

echo "ZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpwID0gUGF0aCgiY29tcGFueW9zL3J1bnRpbWUvY2FwYWJpbGl0eV9leHBhbnNpb24ucHkiKQpzID0gcC5yZWFkX3RleHQoZW5jb2Rpbmc9InV0Zi04IikKbWFya2VyID0gIiMgQ09NUEFOWU9TX1NUQUdJTkdfUEFDS0FHRV9GSVhfVjQiCmlmIG1hcmtlciBpbiBzOgogICAgcHJpbnQoIlNUQUdJTkdfUEFDS0FHRV9GSVhfVjQ9QUxSRUFEWV9JTlNUQUxMRUQiKQogICAgcmFpc2UgU3lzdGVtRXhpdCgwKQoKb2xkID0gJycnIGlmIG5vdCBlcnJvcnM6CiAgYT1yb290L21vZHVsZV9wYXRoO2I9cm9vdC90ZXN0X3BhdGgKICBhLnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSk7Yi5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCiAgYS53cml0ZV90ZXh0KG1vZHVsZV9jb250ZW50LGVuY29kaW5nPSJ1dGYtOCIpO2Iud3JpdGVfdGV4dCh0ZXN0X2NvbnRlbnQsZW5jb2Rpbmc9InV0Zi04IikKJycnCgpuZXcgPSAnJycgaWYgbm90IGVycm9yczoKICBhPXJvb3QvbW9kdWxlX3BhdGg7Yj1yb290L3Rlc3RfcGF0aAogIGEucGFyZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKTtiLnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSkKICAjIENPTVBBTllPU19TVEFHSU5HX1BBQ0tBR0VfRklYX1Y0CiAgZm9yIGluaXRfcGF0aCBpbiAoCiAgICAgIHJvb3QvImNvbXBhbnlvcy9fX2luaXRfXy5weSIsCiAgICAgIHJvb3QvImNvbXBhbnlvcy9leHRlbnNpb25zL19faW5pdF9fLnB5IiwKICAgICAgcm9vdC8iY29tcGFueW9zL2V4dGVuc2lvbnMvZ2VuZXJhdGVkL19faW5pdF9fLnB5IiwKICAgICAgcm9vdC8idGVzdHMvX19pbml0X18ucHkiLAogICAgICByb290LyJ0ZXN0cy9nZW5lcmF0ZWQvX19pbml0X18ucHkiLAogICk6CiAgIGluaXRfcGF0aC5wYXJlbnQubWtkaXIocGFyZW50cz1UcnVlLGV4aXN0X29rPVRydWUpCiAgIGlmIG5vdCBpbml0X3BhdGguZXhpc3RzKCk6CiAgICBpbml0X3BhdGgud3JpdGVfdGV4dCgiIixlbmNvZGluZz0idXRmLTgiKQogIGEud3JpdGVfdGV4dChtb2R1bGVfY29udGVudCxlbmNvZGluZz0idXRmLTgiKTtiLndyaXRlX3RleHQodGVzdF9jb250ZW50LGVuY29kaW5nPSJ1dGYtOCIpCicnJwoKaWYgb2xkIG5vdCBpbiBzOgogICAgcmFpc2UgU3lzdGVtRXhpdCgiRVJST1I6IGV4cGVjdGVkIFYzIHN0YWdlX3BsYW4gYmxvY2sgbm90IGZvdW5kOyBubyBjaGFuZ2VzIG1hZGUiKQpwLndyaXRlX3RleHQocy5yZXBsYWNlKG9sZCwgbmV3LCAxKSwgZW5jb2Rpbmc9InV0Zi04IikKcHJpbnQoIlNUQUdJTkdfUEFDS0FHRV9GSVhfVjQ9SU5TVEFMTEVEIik=" | base64 -d > "$PREFIX/tmp/companyos_expansion_v4_patch.py"
python "$PREFIX/tmp/companyos_expansion_v4_patch.py"
rm -f "$PREFIX/tmp/companyos_expansion_v4_patch.py"

echo "aW1wb3J0IHVuaXR0ZXN0CmZyb20gY29tcGFueW9zLnJ1bnRpbWUgaW1wb3J0IGNhcGFiaWxpdHlfZXhwYW5zaW9uIGFzIGMKCmNsYXNzIEV4cGFuc2lvblN0YWdpbmdJbXBvcnRUZXN0cyh1bml0dGVzdC5UZXN0Q2FzZSk6CiAgICBkZWYgdGVzdF9zdGFnZWRfcGFja2FnZV9pbXBvcnRzKHNlbGYpOgogICAgICAgIGdhcD17ImlkIjoiY2FuZGlkYXRlX2dhcF9yYW5rZXIiLCJ0aXRsZSI6IngiLCJyZWFzb24iOiJ4In0KICAgICAgICBtb2R1bGUgPSAiQ0FQQUJJTElUWV9JRD0nY2FuZGlkYXRlX2dhcF9yYW5rZXInXG5kZWYgY2FwYWJpbGl0eV9tYW5pZmVzdCgpOlxuICAgIHJldHVybiB7J2lkJzogQ0FQQUJJTElUWV9JRH1cbmRlZiBldmFsdWF0ZShjb250ZXh0KTpcbiAgICByZXR1cm4geydvayc6IFRydWV9XG4iCiAgICAgICAgdGVzdCA9ICJpbXBvcnQgdW5pdHRlc3RcbmZyb20gY29tcGFueW9zLmV4dGVuc2lvbnMuZ2VuZXJhdGVkLmNhbmRpZGF0ZV9nYXBfcmFua2VyIGltcG9ydCBjYXBhYmlsaXR5X21hbmlmZXN0LCBldmFsdWF0ZVxuY2xhc3MgVCh1bml0dGVzdC5UZXN0Q2FzZSk6XG4gICAgZGVmIHRlc3RfaXQoc2VsZik6XG4gICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoY2FwYWJpbGl0eV9tYW5pZmVzdCgpWydpZCddLCAnY2FuZGlkYXRlX2dhcF9yYW5rZXInKVxuICAgICAgICBzZWxmLmFzc2VydFRydWUoZXZhbHVhdGUoe30pWydvayddKVxuaWYgX19uYW1lX18gPT0gJ19fbWFpbl9fJzpcbiAgICB1bml0dGVzdC5tYWluKClcbiIKICAgICAgICBwbGFuPXsiY2hhbmdlcyI6WwogICAgICAgICAgICB7InBhdGgiOiJ3cm9uZy9tb2R1bGUucHkiLCJjb250ZW50Ijptb2R1bGV9LAogICAgICAgICAgICB7InBhdGgiOiJ3cm9uZy90ZXN0LnB5IiwiY29udGVudCI6dGVzdH0sCiAgICAgICAgXX0KICAgICAgICBjaWQscm9vdCxlcnJvcnM9Yy5zdGFnZV9wbGFuKGdhcCxwbGFuKQogICAgICAgIHNlbGYuYXNzZXJ0RXF1YWwoZXJyb3JzLFtdKQogICAgICAgIG9rLHN0ZXBzPWMudGVzdF9zdGFnZShyb290LGdhcFsiaWQiXSkKICAgICAgICBzZWxmLmFzc2VydFRydWUob2ssc3RlcHMpCgppZiBfX25hbWVfXz09Il9fbWFpbl9fIjoKICAgIHVuaXR0ZXN0Lm1haW4oKQo=" | base64 -d > tests/test_capability_expansion_staging_v4.py

echo "[1/5] Compile"
python -m py_compile companyos/runtime/capability_expansion.py tests/test_capability_expansion_staging_v4.py

echo "[2/5] Staging import test"
python -m unittest tests.test_capability_expansion_staging_v4 -v

echo "[3/5] Run expansion cycle"
scripts/companyos_expandctl once | tee .companyos_runtime/capability_expansion_v4_cycle.json

echo "[4/5] Commit/push"
git add companyos/runtime/capability_expansion.py tests/test_capability_expansion_staging_v4.py
git diff --cached --quiet || git commit -m "Fix isolated capability staging imports"
BRANCH="$(git branch --show-current)"
[ -n "$BRANCH" ] && git push origin "$BRANCH" || true

echo "[5/5] Restart + verify"
scripts/companyosctl restart || true
sleep 8
echo "===== EXPANSION STATUS ====="
scripts/companyos_expandctl status || true
echo "===== INVENTORY ====="
scripts/companyos_expandctl inventory || true
echo "===== SERVICES ====="
scripts/companyosctl status || true

echo "BACKUP=$BK"
echo "COMPANYOS_CAPABILITY_EXPANSION_STAGING_IMPORT_V4=PASS"
