#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail
cd "$HOME/companyos"
source "$HOME/.companyos_launch_env" 2>/dev/null || true
STAMP="$(date +%Y%m%d_%H%M%S)"
BK="$HOME/companyos/.companyos_backups/research_execution_v3_$STAMP"
mkdir -p "$BK"
cp companyos/runtime/profit_opportunity_runtime.py "$BK/" 2>/dev/null || true
cp companyos/runtime/profit_first_dispatcher.py "$BK/" 2>/dev/null || true

echo "ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwppbXBvcnQganNvbixyZSx0aW1lLGhhc2hsaWIKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoClJPT1Q9UGF0aC5ob21lKCkvImNvbXBhbnlvcyIKUlQ9Uk9PVC8iLmNvbXBhbnlvc19ydW50aW1lIgpSRVNFQVJDSD1SVC8iY2Fub25pY2FsX3Jlc2VhcmNoX291dHB1dHMiCkNBTkRJREFURVM9UlQvInByb2ZpdF9maXJzdF9jYW5kaWRhdGVzIgpTVEFURT1SVC8iY2FuZGlkYXRlX2VucmljaG1lbnRfYnJpZGdlX3N0YXRlLmpzb24iCkJBRD0oInJlc2VhcmNoIG1hcmtldHMgYmVmb3JlIGJ1aWxkaW5nIiwicmVzZWFyY2gvYW5hbHlzaXMgb25seSIsImdlbmVyYXRlIGF0IGxlYXN0IiwiZm9yIGVhY2ggY2FuZGlkYXRlIiwidXNlIDAtMTAwIG51bWVyaWMgc2NvcmVzIiwibWFyayBlc3RpbWF0ZXMgaG9uZXN0bHkiLCJwcmVzZXJ2ZSBhbGwgZXh0ZXJuYWwiLCJjb21wYW55b3Mgb3Bwb3J0dW5pdHkgZW5naW5lIHRlc3QiLCJ0aGlzIHN0YWdlIGlzIHJlc2VhcmNoIikKZGVmIGxvYWQocCk6CiB0cnk6cmV0dXJuIGpzb24ubG9hZHMocC5yZWFkX3RleHQoKSkKIGV4Y2VwdDpyZXR1cm4ge30KZGVmIHNhdmUocCx4KToKIHAucGFyZW50Lm1rZGlyKHBhcmVudHM9VHJ1ZSxleGlzdF9vaz1UcnVlKTsgcC53cml0ZV90ZXh0KGpzb24uZHVtcHMoeCxpbmRlbnQ9Mixzb3J0X2tleXM9VHJ1ZSxkZWZhdWx0PXN0cikrIlxuIikKZGVmIHBpY2soZCwqa3MsZGVmYXVsdD1Ob25lKToKIGZvciBrIGluIGtzOgogIGlmIGQuZ2V0KGspIG5vdCBpbiAoTm9uZSwiIixbXSx7fSk6IHJldHVybiBkW2tdCiBmb3IgbmsgaW4gKCJjYW5kaWRhdGUiLCJvcHBvcnR1bml0eSIsImJ1c2luZXNzIiwiYW5hbHlzaXMiLCJtYXJrZXRfYW5hbHlzaXMiLCJlY29ub21pY3MiLCJzY29yZXMiKToKICBuPWQuZ2V0KG5rKQogIGlmIGlzaW5zdGFuY2UobixkaWN0KToKICAgZm9yIGsgaW4ga3M6CiAgICBpZiBuLmdldChrKSBub3QgaW4gKE5vbmUsIiIsW10se30pOiByZXR1cm4gbltrXQogcmV0dXJuIGRlZmF1bHQKZGVmIG51bSh2LGQ9MCk6CiB0cnk6cmV0dXJuIGZsb2F0KHYpCiBleGNlcHQ6cmV0dXJuIGQKZGVmIHByb2Iodik6CiB4PW51bSh2LDApCiBpZiAwPHg8PTE6eCo9MTAwCiByZXR1cm4gbWF4KDAsbWluKDEwMCx4KSkKZGVmIHVybHMoeCk6CiBvdXQ9W10KIGRlZiB3YWxrKHYpOgogIGlmIGlzaW5zdGFuY2UodixkaWN0KToKICAgZm9yIHogaW4gdi52YWx1ZXMoKTp3YWxrKHopCiAgZWxpZiBpc2luc3RhbmNlKHYsbGlzdCk6CiAgIGZvciB6IGluIHY6d2Fsayh6KQogIGVsaWYgaXNpbnN0YW5jZSh2LHN0cik6CiAgIGZvciB1IGluIHJlLmZpbmRhbGwocidodHRwcz86Ly9bXlxccyJcJylcXF0+XSsnLHYpOgogICAgaWYgdSBub3QgaW4gb3V0Om91dC5hcHBlbmQodSkKIHdhbGsoeCk7IHJldHVybiBvdXRbOjIwXQpkZWYgc2VtYW50aWNzKGQpOgoga3M9e3N0cihrKS5sb3dlcigpIGZvciBrIGluIGR9CiB3YW50ZWQ9KCJjdXN0b21lciIsInRhcmdldF9jdXN0b21lciIsImJ1eWVyIiwibWFya2V0IiwicHJvYmxlbSIsImN1c3RvbWVyX3Byb2JsZW0iLCJvZmZlciIsInNlcnZpY2UiLCJwcm9kdWN0IiwiYnVzaW5lc3NfbW9kZWwiLCJyZXZlbnVlX21vZGVsIiwibWVjaGFuaXNtIikKIGg9c3VtKGsgaW4ga3MgZm9yIGsgaW4gd2FudGVkKQogZm9yIG5rIGluICgiY2FuZGlkYXRlIiwib3Bwb3J0dW5pdHkiLCJidXNpbmVzcyIsIm1hcmtldF9hbmFseXNpcyIpOgogIG49ZC5nZXQobmspCiAgaWYgaXNpbnN0YW5jZShuLGRpY3QpOgogICBua3M9e3N0cihrKS5sb3dlcigpIGZvciBrIGluIG59OyBoKz1zdW0oayBpbiBua3MgZm9yIGsgaW4gd2FudGVkKQogcmV0dXJuIGgKZGVmIG5vcm1hbGl6ZShkLHApOgogaWYgbm90IGlzaW5zdGFuY2UoZCxkaWN0KSBvciBzZW1hbnRpY3MoZCk8MjpyZXR1cm4gTm9uZQogdD1qc29uLmR1bXBzKGQsZGVmYXVsdD1zdHIpLmxvd2VyKCkKIGlmIGFueSh4IGluIHQgZm9yIHggaW4gQkFEKSBhbmQgc2VtYW50aWNzKGQpPDM6cmV0dXJuIE5vbmUKIG5hbWU9c3RyKHBpY2soZCwibmFtZSIsIm9wcG9ydHVuaXR5X25hbWUiLCJ2ZW50dXJlX25hbWUiLCJidXNpbmVzc19uYW1lIiwidGl0bGUiLGRlZmF1bHQ9cC5zdGVtKSlbOjE2MF0KIGV2aWRlbmNlPXBpY2soZCwiZXZpZGVuY2UiLCJzb3VyY2VzIiwiY2l0YXRpb25zIiwibWFya2V0X2V2aWRlbmNlIixkZWZhdWx0PVtdKQogdT11cmxzKGQpCiBlYz1sZW4oZXZpZGVuY2UpIGlmIGlzaW5zdGFuY2UoZXZpZGVuY2UsKGxpc3QsZGljdCkpIGVsc2UgKDEgaWYgaXNpbnN0YW5jZShldmlkZW5jZSxzdHIpIGFuZCBldmlkZW5jZS5zdHJpcCgpIGVsc2UgMCkKIGVjPW1heChlYyxsZW4odSkpCiBhY3Rpb249c3RyKHBpY2soZCwibmV4dF9hY3Rpb24iLCJyZWNvbW1lbmRlZF9hY3Rpb24iLCJleGVjdXRpb25fYWN0aW9uIiwiZmlyc3RfYWN0aW9uIiwicmVjb21tZW5kZWRfbmV4dF9zdGVwIixkZWZhdWx0PSIiKSBvciAiIikuc3RyaXAoKQogaWYgZWM8MSBvciBub3QgYWN0aW9uOnJldHVybiBOb25lCiByZXR1cm4gewogICJzY2hlbWEiOiJjb21wYW55b3MuZW5yaWNoZWRfcHJvZml0X2NhbmRpZGF0ZS52MSIsIm5hbWUiOm5hbWUsCiAgImJ1c2luZXNzX21vZGVsIjpwaWNrKGQsImJ1c2luZXNzX21vZGVsIiwibW9kZWwiLCJyZXZlbnVlX21vZGVsIiwibWVjaGFuaXNtIixkZWZhdWx0PSJ1bmtub3duIiksCiAgInRhcmdldF9jdXN0b21lciI6cGljayhkLCJ0YXJnZXRfY3VzdG9tZXIiLCJjdXN0b21lciIsImJ1eWVyIiwiY3VzdG9tZXJfc2VnbWVudCIsZGVmYXVsdD0idW5rbm93biIpLAogICJwcm9ibGVtIjpwaWNrKGQsInByb2JsZW0iLCJjdXN0b21lcl9wcm9ibGVtIiwicGFpbl9wb2ludCIsZGVmYXVsdD0idW5rbm93biIpLAogICJvZmZlciI6cGljayhkLCJvZmZlciIsInNlcnZpY2UiLCJwcm9kdWN0IiwidmFsdWVfcHJvcG9zaXRpb24iLGRlZmF1bHQ9InVua25vd24iKSwKICAibWFya2V0IjpwaWNrKGQsIm1hcmtldCIsImluZHVzdHJ5Iiwic2VjdG9yIiwiY2F0ZWdvcnkiLGRlZmF1bHQ9InVua25vd24iKSwKICAiZXhwZWN0ZWRfcHJvZml0IjpudW0ocGljayhkLCJleHBlY3RlZF9wcm9maXQiLCJwcm9qZWN0ZWRfcHJvZml0IiwiZXhwZWN0ZWRfbmV0X3Byb2ZpdCIsInByb2ZpdCIsZGVmYXVsdD0wKSksCiAgIm1hcmdpbiI6bnVtKHBpY2soZCwiZXhwZWN0ZWRfbWFyZ2luX3BjdCIsIm1hcmdpbl9wY3QiLCJwcm9maXRfbWFyZ2luIiwibWFyZ2luIixkZWZhdWx0PTApKSwKICAicHJvYmFiaWxpdHkiOnByb2IocGljayhkLCJwcm9iYWJpbGl0eV9zdWNjZXNzX3BjdCIsInN1Y2Nlc3NfcHJvYmFiaWxpdHkiLCJwcm9iYWJpbGl0eSIsImNvbmZpZGVuY2UiLGRlZmF1bHQ9MCkpLAogICJldmlkZW5jZV9jb3VudCI6ZWMsImV2aWRlbmNlX3F1YWxpdHkiOnByb2IocGljayhkLCJldmlkZW5jZV9xdWFsaXR5X3BjdCIsImV2aWRlbmNlX3F1YWxpdHkiLCJldmlkZW5jZV9jb25maWRlbmNlIixkZWZhdWx0PTApKSwKICAicmVhZGluZXNzIjpwcm9iKHBpY2soZCwiZXhlY3V0aW9uX3JlYWRpbmVzc19wY3QiLCJleGVjdXRpb25fcmVhZGluZXNzIiwicmVhZGluZXNzIixkZWZhdWx0PTApKSwKICAidGltZV90b19jYXNoX2RheXMiOm1heCguMSxudW0ocGljayhkLCJ0aW1lX3RvX2Nhc2hfZGF5cyIsImRheXNfdG9fY2FzaCIsZGVmYXVsdD0zMCksMzApKSwKICAiY2FwaXRhbF9yZXF1aXJlZCI6bWF4KDAsbnVtKHBpY2soZCwiY2FwaXRhbF9yZXF1aXJlZCIsInN0YXJ0dXBfY29zdCIsInJlcXVpcmVkX2NhcGl0YWwiLCJjb3N0IixkZWZhdWx0PTApKSksCiAgIm5leHRfYWN0aW9uIjphY3Rpb24sImV2aWRlbmNlIjpldmlkZW5jZSBvciB1LCJzb3VyY2VfdXJscyI6dSwic291cmNlX3Jlc2VhcmNoX2FydGlmYWN0IjpzdHIocC5yZWxhdGl2ZV90byhST09UKSksCiAgImVucmljaGVkX2F0X3VuaXgiOnRpbWUudGltZSgpCiB9CmRlZiByZWZyZXNoX2VucmljaG1lbnRzKG1heF9hZ2VfaG91cnM9NzIpOgogQ0FORElEQVRFUy5ta2RpcihwYXJlbnRzPVRydWUsZXhpc3Rfb2s9VHJ1ZSk7IGN1dG9mZj10aW1lLnRpbWUoKS1tYXhfYWdlX2hvdXJzKjM2MDAKIHNjYW5uZWQ9YWNjZXB0ZWQ9cmVqZWN0ZWQ9MDsgd3JpdHRlbj1bXQogaWYgUkVTRUFSQ0guZXhpc3RzKCk6CiAgZm9yIHAgaW4gc29ydGVkKFJFU0VBUkNILnJnbG9iKCIqLmpzb24iKSxrZXk9bGFtYmRhIHg6eC5zdGF0KCkuc3RfbXRpbWUscmV2ZXJzZT1UcnVlKToKICAgaWYgcC5zdGF0KCkuc3RfbXRpbWU8Y3V0b2ZmOmNvbnRpbnVlCiAgIHNjYW5uZWQrPTE7IHJvdz1ub3JtYWxpemUobG9hZChwKSxwKQogICBpZiBub3Qgcm93OiByZWplY3RlZCs9MTsgY29udGludWUKICAgcmF3PWpzb24uZHVtcHMocm93LHNvcnRfa2V5cz1UcnVlLGRlZmF1bHQ9c3RyKQogICBmcD1oYXNobGliLnNoYTI1NihyYXcuZW5jb2RlKCkpLmhleGRpZ2VzdCgpWzoxNl0KICAgc2x1Zz1yZS5zdWIocidbXmEtejAtOV0rJywnXycscm93WyduYW1lJ10ubG93ZXIoKSkuc3RyaXAoJ18nKVs6NzJdIG9yIGZwCiAgIG91dD1DQU5ESURBVEVTL2YiZW5yaWNoZWRfe3NsdWd9X3tmcH0uanNvbiI7IHNhdmUob3V0LHJvdyk7IHdyaXR0ZW4uYXBwZW5kKHN0cihvdXQucmVsYXRpdmVfdG8oUk9PVCkpKTsgYWNjZXB0ZWQrPTEKICAgaWYgYWNjZXB0ZWQ+PTUwOmJyZWFrCiBzdD17InRzIjp0aW1lLnRpbWUoKSwic2Nhbm5lZCI6c2Nhbm5lZCwiYWNjZXB0ZWQiOmFjY2VwdGVkLCJyZWplY3RlZCI6cmVqZWN0ZWQsIndyaXR0ZW4iOndyaXR0ZW59OyBzYXZlKFNUQVRFLHN0KTsgcmV0dXJuIHN0CmlmIF9fbmFtZV9fPT0iX19tYWluX18iOnByaW50KGpzb24uZHVtcHMocmVmcmVzaF9lbnJpY2htZW50cygpLGluZGVudD0yKSkK" | base64 -d > companyos/runtime/candidate_enrichment_bridge.py
echo "ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwppbXBvcnQganNvbixvcyx0aW1lCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aApmcm9tIGNvbXBhbnlvcy5ydW50aW1lLnByb2ZpdF9vcHBvcnR1bml0eV9lbmdpbmUgaW1wb3J0IGRpc3BhdGNoCmZyb20gY29tcGFueW9zLnJ1bnRpbWUuY2FuZGlkYXRlX2VucmljaG1lbnRfYnJpZGdlIGltcG9ydCByZWZyZXNoX2VucmljaG1lbnRzClJUPVBhdGguaG9tZSgpLyJjb21wYW55b3MvLmNvbXBhbnlvc19ydW50aW1lIjsgU1RBVEU9UlQvInByb2ZpdF9vcHBvcnR1bml0eV9ydW50aW1lX3N0YXRlLmpzb24iCmRlZiBydW4oKToKIGludGVydmFsPW1heCg2MCxpbnQob3MuZ2V0ZW52KCJDT01QQU5ZT1NfUFJPRklUX0VOR0lORV9JTlRFUlZBTF9TRUNPTkRTIiwiMzAwIikpKQogd2hpbGUgbm90IChSVC8iU1RPUF9DT05USU5VT1VTIikuZXhpc3RzKCk6CiAgdHJ5Ong9eyJydW5uaW5nIjpUcnVlLCJoZWFsdGh5IjpUcnVlLCJsYXN0X2N5Y2xlX3VuaXgiOnRpbWUudGltZSgpLCJlbnJpY2htZW50IjpyZWZyZXNoX2VucmljaG1lbnRzKCksInJlc3VsdCI6ZGlzcGF0Y2goKX0KICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6eD17InJ1bm5pbmciOlRydWUsImhlYWx0aHkiOkZhbHNlLCJsYXN0X2N5Y2xlX3VuaXgiOnRpbWUudGltZSgpLCJlcnJvciI6cmVwcihlKX0KICBTVEFURS53cml0ZV90ZXh0KGpzb24uZHVtcHMoeCxpbmRlbnQ9Mixzb3J0X2tleXM9VHJ1ZSxkZWZhdWx0PXN0cikpO3RpbWUuc2xlZXAoaW50ZXJ2YWwpCmlmIF9fbmFtZV9fPT0iX19tYWluX18iOnJ1bigpCg==" | base64 -d > companyos/runtime/profit_opportunity_runtime.py
echo "CiMgQ09NUEFOWU9TX1RBUkdFVEVEX0VOUklDSE1FTlRfQ09OVFJBQ1RfVjMKX3Byb2ZpdF9maXJzdF9idWlsZF9nb2FsX3YzX2Jhc2UgPSBidWlsZF9nb2FsCmRlZiBidWlsZF9nb2FsKCk6CiAgICBxID0gbG9hZChST09UIC8gIi5jb21wYW55b3NfcnVudGltZSIgLyAicHJvZml0X2NhbmRpZGF0ZV9lbnJpY2htZW50X3F1ZXVlLmpzb24iLCB7fSkKICAgIHJvd3MgPSBxLmdldCgiY2FuZGlkYXRlcyIsIFtdKSBpZiBpc2luc3RhbmNlKHEsIGRpY3QpIGVsc2UgW10KICAgIGZvY3VzID0gW10KICAgIGZvciByb3cgaW4gcm93c1s6OF06CiAgICAgICAgaWYgaXNpbnN0YW5jZShyb3csIGRpY3QpOgogICAgICAgICAgICBmb2N1cy5hcHBlbmQoeyJuYW1lIjpyb3cuZ2V0KCJuYW1lIiksIm1pc3Npbmdfb3JfYmxvY2tpbmciOnJvdy5nZXQoIm1pc3Npbmdfb3JfYmxvY2tpbmciKSwiY3VycmVudCI6cm93LmdldCgiY3VycmVudCIpfSkKICAgIHJldHVybiBfcHJvZml0X2ZpcnN0X2J1aWxkX2dvYWxfdjNfYmFzZSgpICsgIiIiClRBUkdFVEVEIEVOUklDSE1FTlQgQ09OVFJBQ1Q6Ci0gUHJpb3JpdGl6ZSB0aGUgY3VycmVudCBlbnJpY2htZW50IHF1ZXVlIGluc3RlYWQgb2YgYnJvYWQgZ2VuZXJpYyByZXNlYXJjaC4KLSBSZXNvbHZlIHNwZWNpZmljIGdhcHMgd2l0aCByZWFsIGV2aWRlbmNlLgotIEEgdXNhYmxlIGNhbmRpZGF0ZSBuZWVkcyBhIGJ1eWVyLCBwcm9ibGVtLCBvZmZlci9yZXZlbnVlIG1lY2hhbmlzbSwgYXQgbGVhc3Qgb25lIGV2aWRlbmNlIHNvdXJjZSwgYW5kIG9uZSBleGVjdXRhYmxlIG5leHQgYWN0aW9uLgotIEVzdGltYXRlIHByb2ZpdCwgcHJvYmFiaWxpdHksIHJlYWRpbmVzcywgdGltZS10by1jYXNoLCBhbmQgY2FwaXRhbCBvbmx5IHdoZW4gZXZpZGVuY2Ugc3VwcG9ydHMgaXQuCi0gTmV2ZXIgaW52ZW50IGV2aWRlbmNlLCBjdXN0b21lcnMsIHJldmVudWUsIG9yIHByb2JhYmlsaXR5LgotIFNhdmUgc3RydWN0dXJlZCBjb21tZXJjaWFsIHJlc2VhcmNoIGludG8gY2Fub25pY2FsX3Jlc2VhcmNoX291dHB1dHMgZm9yIGluZ2VzdGlvbi4KLSBBdm9pZCBkdXBsaWNhdGUgb3IgcmVuYW1lZCBvcHBvcnR1bml0aWVzLgotIFByZXNlcnZlIGFsbCBjb25uZWN0b3IsIGFwcHJvdmFsLCBmaW5hbmNlLCBjcmVkZW50aWFsLCBzaWduZXIsIGRlcGxveW1lbnQsIGxlZ2FsLCBkZXN0cnVjdGl2ZS1hY3Rpb24sIGFuZCBpcnJldmVyc2libGUtYWN0aW9uIGdhdGVzLgpDVVJSRU5UIEVOUklDSE1FTlQgUVVFVUU6CiIiIiArIGpzb24uZHVtcHMoZm9jdXMsIGluZGVudD0yLCBkZWZhdWx0PXN0cikK" | base64 -d > "$PREFIX/tmp/companyos_goal_append.py"

python - "$PREFIX/tmp/companyos_goal_append.py" <<'PY'
from pathlib import Path
import sys
target=Path("companyos/runtime/profit_first_dispatcher.py")
append=Path(sys.argv[1]).read_text()
s=target.read_text()
if "# COMPANYOS_TARGETED_ENRICHMENT_CONTRACT_V3" not in s:
    target.write_text(s+"\n"+append+"\n")
    print("TARGETED_ENRICHMENT_DISPATCHER=INSTALLED")
else:
    print("TARGETED_ENRICHMENT_DISPATCHER=ALREADY_INSTALLED")
PY
rm -f "$PREFIX/tmp/companyos_goal_append.py"

python -m py_compile companyos/runtime/candidate_enrichment_bridge.py companyos/runtime/profit_opportunity_runtime.py companyos/runtime/profit_first_dispatcher.py
python -m companyos.runtime.candidate_enrichment_bridge

python - <<'PY'
from companyos.runtime.profit_first_dispatcher import build_goal
g=build_goal()
assert "TARGETED ENRICHMENT CONTRACT" in g
print("TARGETED_ENRICHMENT_GOAL=PASS")
PY

git add companyos/runtime/candidate_enrichment_bridge.py companyos/runtime/profit_opportunity_runtime.py companyos/runtime/profit_first_dispatcher.py
git diff --cached --quiet || git commit -m "Convert targeted research into execution-qualified candidates"
BRANCH="$(git branch --show-current)"
[ -n "$BRANCH" ] && git push origin "$BRANCH" || true

scripts/companyosctl restart || true
sleep 8

python - <<'PY'
import json
from companyos.runtime.profit_first_dispatcher import maybe_dispatch
print(json.dumps(maybe_dispatch(min_idle_cycles=0,cooldown_seconds=0),indent=2,sort_keys=True,default=str))
PY

echo "===== BRIDGE STATE ====="
cat .companyos_runtime/candidate_enrichment_bridge_state.json 2>/dev/null || true
echo "===== PROFIT STATUS ====="
python - <<'PY'
from companyos.runtime.profit_opportunity_engine import choose
x=choose()
print("candidate_count =",x.get("candidate_count"))
print("eligible_count =",x.get("eligible_count"))
print("decision =",x.get("decision"))
print("chosen =", (x.get("chosen") or {}).get("name"))
print("enrichment_queue_count =",x.get("enrichment_queue_count"))
PY
echo "===== SERVICES ====="
scripts/companyosctl status || true
echo "COMPANYOS_RESEARCH_EXECUTION_CONVERSION_FIX_V3_1=PASS"
