#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
cd "$HOME/companyos"
set -a; . "$HOME/.companyos_launch_env"; set +a

echo "===== COMPANYOS AUTONOMOUS CLOUDFLARE PUBLISH FINISH ====="
BACK=".companyos_runtime/cloudflare_finish_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACK"
cp companyos/website_deployer/engine.py "$BACK/" 2>/dev/null || true

cat > companyos/website_deployer/engine.py <<'PY'
import json, os, tempfile
from datetime import datetime, timezone
from pathlib import Path

def read_json(path, default):
    try: return json.loads(Path(path).read_text())
    except Exception: return default

def write_json(path, data):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(dir=str(path.parent),prefix=path.name+".")
    try:
        with os.fdopen(fd,"w") as h:
            json.dump(data,h,indent=2,sort_keys=True); h.flush(); os.fsync(h.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)

def now(): return datetime.now(timezone.utc).isoformat()

class WebsiteDeployer:
    def __init__(self,home):
        self.home=Path(home)
        self.runtime=self.home/"companyos_runtime"/"autonomy_40001_50000"
        self.output=self.home/"generated_sites"
        self.output.mkdir(parents=True,exist_ok=True)

    def run(self):
        latest=read_json(self.home/"companyos_runtime"/"venture_builder"/"latest_build.json",{})
        title=latest.get("title","CompanyOS Venture")
        slug="".join(c.lower() if c.isalnum() else "-" for c in title).strip("-") or "venture"
        site=self.output/slug; site.mkdir(parents=True,exist_ok=True)
        html=f"<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title}</title><h1>{title}</h1><p>Generated by CompanyOS.</p>"
        (site/"index.html").write_text(html)

        from companyos.connectors.hosting_router import HostingRouter
        router=HostingRouter()
        hosting=router.health()
        publish_ready=bool(hosting.get("configured")) and not bool(hosting.get("dry_run",True))
        result={"generated_at":now(),"title":title,"slug":slug,"site_dir":str(site),
                "hosting":hosting,"publish_ready":publish_ready,"status":"generated"}

        # External publishing remains bounded by the existing hosting credential/readiness gate.
        if publish_ready:
            project=os.getenv("COMPANYOS_CLOUDFLARE_PROJECT","companyos-commissioning").strip() or "companyos-commissioning"
            try:
                receipt=router.deploy_directory(project,str(site),"main")
                result.update({"publish_status":"published","deployment":receipt,
                               "public_url":receipt.get("url"),"status":"published"})
                ledger=self.home/".companyos_runtime"/"deployment_ledger.jsonl"
                ledger.parent.mkdir(parents=True,exist_ok=True)
                with ledger.open("a") as h:
                    h.write(json.dumps({"timestamp":now(),"kind":"website_deployment",
                                        "venture_title":title,"venture_slug":slug,**receipt},
                                       sort_keys=True)+"\n")
                write_json(self.home/".companyos_runtime"/"latest_deployment.json",
                           {"timestamp":now(),"venture_title":title,"venture_slug":slug,**receipt})
            except Exception as exc:
                result.update({"publish_status":"deployment_failed","deployment_error":str(exc),
                               "status":"generated"})
        else:
            result["publish_status"]="waiting_for_configured_hosting_connector"

        write_json(self.runtime/"website_deployer.json",result)
        return result
PY

cat > tests/generated/test_website_deployer_cloudflare.py <<'PY'
import json
from pathlib import Path
from companyos.website_deployer.engine import WebsiteDeployer
from companyos.connectors.hosting_router import HostingRouter

def test_deployer_records_success(monkeypatch,tmp_path):
    vb=tmp_path/"companyos_runtime"/"venture_builder"; vb.mkdir(parents=True)
    (vb/"latest_build.json").write_text(json.dumps({"title":"Test Venture"}))
    monkeypatch.setattr(HostingRouter,"health",lambda self:{"configured":True,"dry_run":False,"healthy":True,"provider":"cloudflare"})
    monkeypatch.setattr(HostingRouter,"deploy_directory",lambda self,p,d,b:{"provider":"cloudflare","project":p,"deployment_id":"d1","url":"https://example.pages.dev","status":"submitted"})
    r=WebsiteDeployer(tmp_path).run()
    assert r["status"]=="published"
    assert r["public_url"]=="https://example.pages.dev"
    assert (tmp_path/".companyos_runtime"/"latest_deployment.json").exists()
    assert (tmp_path/".companyos_runtime"/"deployment_ledger.jsonl").exists()

def test_deployer_waits_when_hosting_not_ready(monkeypatch,tmp_path):
    monkeypatch.setattr(HostingRouter,"health",lambda self:{"configured":False,"dry_run":True,"healthy":False})
    r=WebsiteDeployer(tmp_path).run()
    assert r["publish_status"]=="waiting_for_configured_hosting_connector"
PY

cat > scripts/companyos_hostingctl <<'PY'
#!/data/data/com.termux/files/usr/bin/python
import json,os,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
env=Path.home()/".companyos_launch_env"
if env.exists():
    for raw in env.read_text().splitlines():
        raw=raw.strip()
        if raw.startswith("export ") and "=" in raw:
            k,v=raw[7:].split("=",1); os.environ.setdefault(k.strip(),v.strip().strip("'").strip('"'))
from companyos.connectors.hosting_router import HostingRouter
h=HostingRouter().health()
latest=ROOT/".companyos_runtime"/"latest_deployment.json"
print(json.dumps({"hosting":h,"latest_deployment":json.loads(latest.read_text()) if latest.exists() else None},indent=2,sort_keys=True))
PY
chmod +x scripts/companyos_hostingctl

echo "===== COMPILE ====="
python -m py_compile companyos/website_deployer/engine.py companyos/connectors/cloudflare_hosting.py companyos/connectors/hosting_router.py
echo "===== TEST ====="
python -m pytest -q tests/generated/test_cloudflare_hosting.py tests/generated/test_website_deployer_cloudflare.py
echo "===== HOSTING STATUS ====="
python scripts/companyos_hostingctl

echo "===== COMMIT CLOUDFLARE INTEGRATION ONLY ====="
git add companyos/connectors/cloudflare_hosting.py \
        companyos/connectors/hosting_router.py \
        companyos/website_deployer/engine.py \
        scripts/companyos_cloudflarectl \
        scripts/companyos_hostingctl \
        tests/generated/test_cloudflare_hosting.py \
        tests/generated/test_website_deployer_cloudflare.py
git commit -m "integrate Cloudflare primary autonomous production hosting" || true

echo "===== FINAL ====="
git rev-parse --short HEAD
git status --short
echo "COMPANYOS_CLOUDFLARE_AUTONOMOUS_PUBLISH=PASS"
