#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail
cd "$HOME/companyos"

STAMP="$(date +%Y%m%d_%H%M%S)"
BK="$HOME/companyos/.companyos_backups/stale_pid_recovery_v21_$STAMP"
mkdir -p "$BK"
cp -a companyos/runtime/runtime_control.py "$BK/" 2>/dev/null || true
cp -a scripts/companyosctl "$BK/" 2>/dev/null || true

echo "ZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpwID0gUGF0aCgiY29tcGFueW9zL3J1bnRpbWUvcnVudGltZV9jb250cm9sLnB5IikKcyA9IHAucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpCgppZiAiIyBDT01QQU5ZT1NfU1RBTEVfUElEX1JFQ09WRVJZX1YyMSIgaW4gczoKICAgIHByaW50KCJTVEFMRV9QSURfUkVDT1ZFUllfVjIxPUFMUkVBRFlfSU5TVEFMTEVEIikKICAgIHJhaXNlIFN5c3RlbUV4aXQoMCkKCmhlbHBlciA9ICcnJwojIENPTVBBTllPU19TVEFMRV9QSURfUkVDT1ZFUllfVjIxCmRlZiBfcGlkX2lzX2FsaXZlKHBpZCk6CiAgICB0cnk6CiAgICAgICAgaWYgbm90IHBpZCBvciBpbnQocGlkKSA8PSAxOgogICAgICAgICAgICByZXR1cm4gRmFsc2UKICAgICAgICBvcy5raWxsKGludChwaWQpLCAwKQogICAgICAgIHJldHVybiBUcnVlCiAgICBleGNlcHQgUHJvY2Vzc0xvb2t1cEVycm9yOgogICAgICAgIHJldHVybiBGYWxzZQogICAgZXhjZXB0IFBlcm1pc3Npb25FcnJvcjoKICAgICAgICByZXR1cm4gVHJ1ZQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gRmFsc2UKCmRlZiBfcmVhZF9waWRfZmlsZShwYXRoKToKICAgIHRyeToKICAgICAgICByZXR1cm4gaW50KFBhdGgocGF0aCkucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpLnN0cmlwKCkpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBOb25lCgpkZWYgX2NsZWFyX3N0YWxlX3N1cGVydmlzb3Jfc3RhdGUoc2VsZik6CiAgICBwaWQgPSBfcmVhZF9waWRfZmlsZShzZWxmLnN1cGVydmlzb3JfcGlkKQogICAgaWYgcGlkIGFuZCBub3QgX3BpZF9pc19hbGl2ZShwaWQpOgogICAgICAgIHRyeToKICAgICAgICAgICAgUGF0aChzZWxmLnN1cGVydmlzb3JfcGlkKS51bmxpbmsobWlzc2luZ19vaz1UcnVlKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIHBhc3MKCiAgICB0cnk6CiAgICAgICAgc3RhdGUgPSBzZWxmLnN0YXR1cygpCiAgICAgICAgc3RhdGVfcGlkID0gc3RhdGUuZ2V0KCJzdXBlcnZpc29yX3BpZCIpCiAgICAgICAgaWYgc3RhdGVfcGlkIGFuZCBub3QgX3BpZF9pc19hbGl2ZShzdGF0ZV9waWQpOgogICAgICAgICAgICBzdGF0ZVsic3VwZXJ2aXNvcl9waWQiXSA9IE5vbmUKICAgICAgICAgICAgc3RhdGVbInN1cGVydmlzb3JfYWxpdmUiXSA9IEZhbHNlCiAgICAgICAgICAgIHN0YXRlWyJzdG9wX3JlcXVlc3RlZCJdID0gRmFsc2UKICAgICAgICAgICAgUGF0aChzZWxmLnN0YXRlX3BhdGgpLndyaXRlX3RleHQoanNvbi5kdW1wcyhzdGF0ZSwgaW5kZW50PTIpICsgIlxuIiwgZW5jb2Rpbmc9InV0Zi04IikKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgcGFzcwoKICAgIHJldHVybiB7InBpZF9maWxlX3BpZCI6IHBpZCwgInBpZF9maWxlX2FsaXZlIjogX3BpZF9pc19hbGl2ZShwaWQpIGlmIHBpZCBlbHNlIEZhbHNlfQonJycKCmFuY2hvciA9ICJjbGFzcyBVbmlmaWVkUnVudGltZUNvbnRyb2w6IgppZiBhbmNob3Igbm90IGluIHM6CiAgICByYWlzZSBTeXN0ZW1FeGl0KCJFUlJPUjogVW5pZmllZFJ1bnRpbWVDb250cm9sIGNsYXNzIG5vdCBmb3VuZCIpCgpzID0gcy5yZXBsYWNlKGFuY2hvciwgaGVscGVyICsgIlxuXG4iICsgYW5jaG9yLCAxKQoKc3RhcnRfc2lnID0gIiAgICBkZWYgc3RhcnQoc2VsZiwgd2FpdF9zZWNvbmRzOiBmbG9hdCA9IDE1LjApIC0+IGRpY3Rbc3RyLCBBbnldOlxuIgppZiBzdGFydF9zaWcgbm90IGluIHM6CiAgICByYWlzZSBTeXN0ZW1FeGl0KCJFUlJPUjogc3RhcnQgbWV0aG9kIHNpZ25hdHVyZSBub3QgZm91bmQiKQoKcyA9IHMucmVwbGFjZSgKICAgIHN0YXJ0X3NpZywKICAgIHN0YXJ0X3NpZyArICIgICAgICAgIHNlbGYuX2NsZWFyX3N0YWxlX3N1cGVydmlzb3Jfc3RhdGUoKVxuIiwKICAgIDEsCikKCnMgPSBzLnJlcGxhY2UoCiAgICAiY2xhc3MgVW5pZmllZFJ1bnRpbWVDb250cm9sOlxuIiwKICAgICJjbGFzcyBVbmlmaWVkUnVudGltZUNvbnRyb2w6XG4gICAgX2NsZWFyX3N0YWxlX3N1cGVydmlzb3Jfc3RhdGUgPSBfY2xlYXJfc3RhbGVfc3VwZXJ2aXNvcl9zdGF0ZVxuIiwKICAgIDEsCikKCnAud3JpdGVfdGV4dChzLCBlbmNvZGluZz0idXRmLTgiKQpwcmludCgiU1RBTEVfUElEX1JFQ09WRVJZX1YyMT1JTlNUQUxMRUQiKQo=" | base64 -d > "$PREFIX/tmp/companyos_stale_pid_patch_v21.py"
python "$PREFIX/tmp/companyos_stale_pid_patch_v21.py"
rm -f "$PREFIX/tmp/companyos_stale_pid_patch_v21.py"

echo "aW1wb3J0IG9zLCB0ZW1wZmlsZSwgdW5pdHRlc3QKZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCmZyb20gY29tcGFueW9zLnJ1bnRpbWUucnVudGltZV9jb250cm9sIGltcG9ydCBfcGlkX2lzX2FsaXZlLCBfcmVhZF9waWRfZmlsZQoKY2xhc3MgUnVudGltZUNvbnRyb2xTdGFsZVBpZFJlY292ZXJ5VjIxVGVzdHModW5pdHRlc3QuVGVzdENhc2UpOgogICAgZGVmIHRlc3RfY3VycmVudF9waWRfaXNfYWxpdmUoc2VsZik6CiAgICAgICAgc2VsZi5hc3NlcnRUcnVlKF9waWRfaXNfYWxpdmUob3MuZ2V0cGlkKCkpKQoKICAgIGRlZiB0ZXN0X2ltcG9zc2libGVfcGlkX2lzX2RlYWQoc2VsZik6CiAgICAgICAgc2VsZi5hc3NlcnRGYWxzZShfcGlkX2lzX2FsaXZlKDk5OTk5OSkpCgogICAgZGVmIHRlc3RfcmVhZF9waWRfZmlsZShzZWxmKToKICAgICAgICB3aXRoIHRlbXBmaWxlLlRlbXBvcmFyeURpcmVjdG9yeSgpIGFzIHRkOgogICAgICAgICAgICBwID0gUGF0aCh0ZCkgLyAicGlkIgogICAgICAgICAgICBwLndyaXRlX3RleHQoIjEyM1xuIikKICAgICAgICAgICAgc2VsZi5hc3NlcnRFcXVhbChfcmVhZF9waWRfZmlsZShwKSwgMTIzKQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHVuaXR0ZXN0Lm1haW4oKQo=" | base64 -d > tests/test_runtime_control_stale_pid_recovery_v21.py
echo "IyEvZGF0YS9kYXRhL2NvbS50ZXJtdXgvZmlsZXMvdXNyL2Jpbi9iYXNoCnNldCAtRWV1byBwaXBlZmFpbApjZCAiJEhPTUUvY29tcGFueW9zIgoKZWNobyAiPT09PT0gUFJFLVJFQ09WRVJZID09PT09IgpzY3JpcHRzL2NvbXBhbnlvc2N0bCBzdGF0dXMgfHwgdHJ1ZQoKcHl0aG9uIC0gPDwnUFknCmltcG9ydCBqc29uLCBvcwpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCnJ0ID0gUGF0aCgiLmNvbXBhbnlvc19ydW50aW1lIikKcGlkZmlsZSA9IHJ0IC8gInNlcnZpY2Vfc3VwZXJ2aXNvci5waWQiCnN0YXRlZmlsZSA9IHJ0IC8gInNlcnZpY2Vfc3VwZXJ2aXNvcl9zdGF0ZS5qc29uIgoKZGVmIGFsaXZlKHBpZCk6CiAgICB0cnk6CiAgICAgICAgaWYgbm90IHBpZCBvciBpbnQocGlkKSA8PSAxOgogICAgICAgICAgICByZXR1cm4gRmFsc2UKICAgICAgICBvcy5raWxsKGludChwaWQpLCAwKQogICAgICAgIHJldHVybiBUcnVlCiAgICBleGNlcHQgUHJvY2Vzc0xvb2t1cEVycm9yOgogICAgICAgIHJldHVybiBGYWxzZQogICAgZXhjZXB0IFBlcm1pc3Npb25FcnJvcjoKICAgICAgICByZXR1cm4gVHJ1ZQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gRmFsc2UKCnBpZCA9IE5vbmUKaWYgcGlkZmlsZS5leGlzdHMoKToKICAgIHRyeToKICAgICAgICBwaWQgPSBpbnQocGlkZmlsZS5yZWFkX3RleHQoKS5zdHJpcCgpKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBwaWQgPSBOb25lCgpwcmludCgicGlkZmlsZV9waWQ9IiwgcGlkKQpwcmludCgicGlkZmlsZV9hbGl2ZT0iLCBhbGl2ZShwaWQpIGlmIHBpZCBlbHNlIEZhbHNlKQoKaWYgcGlkIGFuZCBub3QgYWxpdmUocGlkKToKICAgIHBpZGZpbGUudW5saW5rKG1pc3Npbmdfb2s9VHJ1ZSkKICAgIHByaW50KCJzdGFsZV9waWRfZmlsZV9yZW1vdmVkPXRydWUiKQoKaWYgc3RhdGVmaWxlLmV4aXN0cygpOgogICAgdHJ5OgogICAgICAgIGQgPSBqc29uLmxvYWRzKHN0YXRlZmlsZS5yZWFkX3RleHQoKSkKICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgZCA9IHt9CiAgICBzcGlkID0gZC5nZXQoInN1cGVydmlzb3JfcGlkIikKICAgIGlmIHNwaWQgYW5kIG5vdCBhbGl2ZShzcGlkKToKICAgICAgICBkWyJzdXBlcnZpc29yX3BpZCJdID0gTm9uZQogICAgICAgIGRbInN1cGVydmlzb3JfYWxpdmUiXSA9IEZhbHNlCiAgICAgICAgZFsic3RvcF9yZXF1ZXN0ZWQiXSA9IEZhbHNlCiAgICAgICAgc3RhdGVmaWxlLndyaXRlX3RleHQoanNvbi5kdW1wcyhkLCBpbmRlbnQ9MikgKyAiXG4iKQogICAgICAgIHByaW50KCJzdGFsZV9zdGF0ZV9jbGVhcmVkPXRydWUiKQpQWQoKZWNobyAiPT09PT0gU1RBUlQgPT09PT0iCnNjcmlwdHMvY29tcGFueW9zY3RsIHN0YXJ0IHx8IHRydWUKc2xlZXAgMTIKCmVjaG8gIj09PT09IFBPU1QtU1RBUlQgU1RBVFVTID09PT09IgpzY3JpcHRzL2NvbXBhbnlvc2N0bCBzdGF0dXMgfHwgdHJ1ZQoKZWNobyAiPT09PT0gSEVBTFRIID09PT09IgpzY3JpcHRzL2NvbXBhbnlvc2N0bCBoZWFsdGggfHwgdHJ1ZQo=" | base64 -d > scripts/companyos_recover_supervisor
chmod +x scripts/companyos_recover_supervisor

echo "[1/6] Compile"
python -m py_compile companyos/runtime/runtime_control.py tests/test_runtime_control_stale_pid_recovery_v21.py

echo "[2/6] Unit tests"
python -m unittest tests.test_runtime_control_stale_pid_recovery_v21 -v

echo "[3/6] Recovery run"
scripts/companyos_recover_supervisor | tee .companyos_runtime/stale_pid_recovery_v21.log

echo "[4/6] Verify supervisor process"
python - <<'PY'
import json, os
from pathlib import Path
p = Path(".companyos_runtime/service_supervisor_state.json")
d = json.loads(p.read_text()) if p.exists() else {}
pid = d.get("supervisor_pid")
alive = False
if pid:
    try:
        os.kill(int(pid), 0)
        alive = True
    except Exception:
        alive = False
print("SUPERVISOR_PID=", pid)
print("SUPERVISOR_ALIVE=", alive)
print("STOP_REQUESTED=", d.get("stop_requested"))
if not alive:
    raise SystemExit("ERROR: supervisor did not recover")
PY

echo "[5/6] Commit/push"
git add companyos/runtime/runtime_control.py scripts/companyos_recover_supervisor tests/test_runtime_control_stale_pid_recovery_v21.py
git diff --cached --quiet || git commit -m "Repair stale supervisor PID recovery and startup"
BRANCH="$(git branch --show-current)"
[ -n "$BRANCH" ] && git push origin "$BRANCH" || true

echo "[6/6] Final health"
scripts/companyosctl status || true
scripts/companyosctl health || true

echo "BACKUP=$BK"
echo "COMPANYOS_STALE_PID_SUPERVISOR_RECOVERY_V21=PASS"
