import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

def read_json(path, default):
    try:
        return json.loads(Path(path).read_text())
    except Exception:
        return default

def write_json(path, data):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".")
    try:
        with os.fdopen(fd, "w") as handle:
            json.dump(data, handle, indent=2, sort_keys=True)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)

def now():
    return datetime.now(timezone.utc).isoformat()

class WebsiteDeployer:
    def __init__(self, home):
        self.home=home
        self.runtime=home/"companyos_runtime"/"autonomy_40001_50000"
        self.output=home/"generated_sites"
        self.output.mkdir(parents=True, exist_ok=True)

    def run(self):
        latest=read_json(self.home/"companyos_runtime"/"venture_builder"/"latest_build.json",{})
        title=latest.get("title","CompanyOS Venture")
        slug="".join(c.lower() if c.isalnum() else "-" for c in title).strip("-") or "venture"
        site=self.output/slug
        site.mkdir(parents=True, exist_ok=True)
        html=f"<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title}</title><h1>{title}</h1><p>Generated by CompanyOS.</p>"
        (site/"index.html").write_text(html)
        connectors=read_json(self.home/"companyos_runtime"/"connectors"/"health.json",{}).get("connectors",{})
        hosting=connectors.get("hosting",{})
        publish_ready=bool(hosting.get("configured")) and not bool(hosting.get("dry_run",True))
        result={"generated_at":now(),"site_dir":str(site),"publish_ready":publish_ready,"publish_status":"ready_for_connector" if publish_ready else "waiting_for_configured_hosting_connector","status":"generated"}
        write_json(self.runtime/"website_deployer.json",result)
        return result
