import json, os, tempfile
from datetime import datetime, timezone
from pathlib import Path

def read_json(path, default):
    try: return json.loads(Path(path).read_text())
    except Exception: return default

def write_json(path, data):
    path=Path(path); path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(dir=str(path.parent),prefix=path.name+".")
    try:
        with os.fdopen(fd,"w") as h:
            json.dump(data,h,indent=2,sort_keys=True); h.flush(); os.fsync(h.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)

def now(): return datetime.now(timezone.utc).isoformat()

class WebsiteDeployer:
    def __init__(self,home):
        self.home=Path(home)
        self.runtime=self.home/"companyos_runtime"/"autonomy_40001_50000"
        self.output=self.home/"generated_sites"
        self.output.mkdir(parents=True,exist_ok=True)

    def run(self):
        latest=read_json(self.home/"companyos_runtime"/"venture_builder"/"latest_build.json",{})
        title=latest.get("title","CompanyOS Venture")
        slug="".join(c.lower() if c.isalnum() else "-" for c in title).strip("-") or "venture"
        site=self.output/slug; site.mkdir(parents=True,exist_ok=True)
        html=f"<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title}</title><h1>{title}</h1><p>Generated by CompanyOS.</p>"
        (site/"index.html").write_text(html)

        from companyos.connectors.hosting_router import HostingRouter
        router=HostingRouter()
        hosting=router.health()
        publish_ready=bool(hosting.get("configured")) and not bool(hosting.get("dry_run",True))
        result={"generated_at":now(),"title":title,"slug":slug,"site_dir":str(site),
                "hosting":hosting,"publish_ready":publish_ready,"status":"generated"}

        # External publishing remains bounded by the existing hosting credential/readiness gate.
        if publish_ready:
            project=os.getenv("COMPANYOS_CLOUDFLARE_PROJECT","companyos-commissioning").strip() or "companyos-commissioning"
            try:
                receipt=router.deploy_directory(project,str(site),"main")
                result.update({"publish_status":"published","deployment":receipt,
                               "public_url":receipt.get("url"),"status":"published"})
                ledger=self.home/".companyos_runtime"/"deployment_ledger.jsonl"
                ledger.parent.mkdir(parents=True,exist_ok=True)
                with ledger.open("a") as h:
                    h.write(json.dumps({"timestamp":now(),"kind":"website_deployment",
                                        "venture_title":title,"venture_slug":slug,**receipt},
                                       sort_keys=True)+"\n")
                write_json(self.home/".companyos_runtime"/"latest_deployment.json",
                           {"timestamp":now(),"venture_title":title,"venture_slug":slug,**receipt})
            except Exception as exc:
                result.update({"publish_status":"deployment_failed","deployment_error":str(exc),
                               "status":"generated"})
        else:
            result["publish_status"]="waiting_for_configured_hosting_connector"

        write_json(self.runtime/"website_deployer.json",result)
        return result
