import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

def read_json(path, default):
    try:
        return json.loads(Path(path).read_text())
    except Exception:
        return default

def write_json(path, data):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".")
    try:
        with os.fdopen(fd, "w") as handle:
            json.dump(data, handle, indent=2, sort_keys=True)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)

def now():
    return datetime.now(timezone.utc).isoformat()

class CodeGenerationEngine:
    def __init__(self, home):
        self.home=home
        self.runtime=home/"companyos_runtime"/"autonomy_40001_50000"
        self.output=home/"generated_code"
        self.output.mkdir(parents=True, exist_ok=True)

    def run(self):
        latest=read_json(self.home/"companyos_runtime"/"venture_builder"/"latest_build.json",{})
        title=latest.get("title","CompanyOS Generated Product")
        slug="".join(c.lower() if c.isalnum() else "-" for c in title).strip("-") or "product"
        project=self.output/slug
        project.mkdir(parents=True, exist_ok=True)
        app_code=(
            "from flask import Flask, jsonify\\n"
            "app=Flask(__name__)\\n"
            "@app.get('/health')\\n"
            "def health(): return jsonify({'ok':True})\\n"
            "if __name__=='__main__': app.run(host='127.0.0.1',port=5051)\\n"
        )
        (project/"app.py").write_text(app_code)
        (project/"requirements.txt").write_text("flask>=3.0\\n")
        (project/"README.md").write_text(f"# {title}\\n\\nGenerated by CompanyOS.\\n")
        result={"phase":"40001-50000","generated_at":now(),"project":str(project),"files":["app.py","requirements.txt","README.md"],"test_status":"local_scaffold_ready","status":"generated"}
        write_json(self.runtime/"code_generation.json",result)
        return result
