#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
ROOT="${1:-$HOME/companyos}"
HERE="$(cd "$(dirname "$0")" && pwd)"
STAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP="$ROOT/backups/phase5001_5500_growth_ops_$STAMP"
echo "=== CompanyOS Phase 5001-5500 ==="
echo "AUTONOMOUS MARKET INTELLIGENCE + GROWTH"
[ -d "$ROOT" ] || { echo "ERROR: $ROOT missing"; exit 1; }
mkdir -p "$BACKUP" "$ROOT/scripts" "$ROOT/tests"
cp -r "$HERE/companyos" "$ROOT/"
cp "$HERE/scripts/"* "$ROOT/scripts/"
cp "$HERE/tests/"* "$ROOT/tests/"
chmod +x "$ROOT/scripts/phase5001_5500_verify.py" "$ROOT/scripts/run_phase5500_growth_ops_demo.py" "$ROOT/scripts/companyos_growth_ops.sh"
cd "$ROOT"
export PYTHONPATH="$ROOT:$ROOT/src${PYTHONPATH:+:$PYTHONPATH}"
python scripts/phase5001_5500_verify.py
python -m pytest -q tests/test_phase5001_5500.py --disable-warnings
echo
echo "PHASE5001_5500_INSTALL_OK"
echo "MARKET_RADAR=READY"
echo "COMPETITOR_INTELLIGENCE=READY"
echo "CUSTOMER_SIGNAL_ENGINE=READY"
echo "OPPORTUNITY_RANKER=READY"
echo "EXPERIMENT_ENGINE=READY"
echo "PRICING_OPTIMIZER=READY"
echo "RETENTION_ENGINE=READY"
echo "CHANNEL_ALLOCATOR=READY"
echo "GROWTH_FORECASTER=READY"
echo "LEARNING_MEMORY=READY"
echo "GROWTH_APPROVAL_ROUTER=READY"
echo "PERSISTENT_GROWTH_STATE=READY"
echo "GROWTH_AUDIT=READY"
echo "CEO_GROWTH_OPS_CONTROLLER=READY"
echo "Backup: $BACKUP"
