#!/usr/bin/env python3

import argparse
import json

from manager import (
    install_plugin,
    list_marketplace,
    uninstall_plugin,
)


def output(data) -> None:
    print(json.dumps(data, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(
        dest="command",
        required=True,
    )

    commands.add_parser("list")

    install_parser = commands.add_parser("install")
    install_parser.add_argument("plugin_id")

    uninstall_parser = commands.add_parser("uninstall")
    uninstall_parser.add_argument("plugin_id")

    args = parser.parse_args()

    if args.command == "list":
        output(list_marketplace())
    elif args.command == "install":
        output(install_plugin(args.plugin_id))
    elif args.command == "uninstall":
        output(uninstall_plugin(args.plugin_id))


if __name__ == "__main__":
    main()
