#!/usr/bin/env python3
import json,sys,time,shutil,subprocess
from pathlib import Path
RT=Path.home()/"companyos"/".companyos_runtime"
READY=RT/"launch_ready"; PLANS=RT/"execution_plans"; BUILDS=RT/"product_builds"; REPORTS=RT/"build_reports"; STATE=RT/"product_builder_state.json"
for p in (BUILDS,REPORTS): p.mkdir(parents=True,exist_ok=True)
def load(p,d):
    try:return json.loads(p.read_text())
    except:return d
def save(p,d): p.write_text(json.dumps(d,indent=2,sort_keys=True)+"\n")
def build():
    results=[]
    for rp in sorted(READY.glob("*.json")):
        r=load(rp,{})
        if not r.get("ready_for_build"): continue
        vid=r.get("venture_id")
        plan=load(PLANS/f"{vid}.json",{})
        name=plan.get("title") or vid
        proj=BUILDS/vid
        if proj.exists(): shutil.rmtree(proj)
        proj.mkdir(parents=True)
        (proj/"app.py").write_text(
            "from http.server import BaseHTTPRequestHandler,HTTPServer\n"
            "import json\n"
            "class Handler(BaseHTTPRequestHandler):\n"
            "    def do_GET(self):\n"
            "        if self.path=='/health':\n"
            f"            body=json.dumps({{'status':'healthy','service':{name!r}}}).encode()\n"
            "        else:\n"
            f"            body={('CompanyOS product: '+str(name))!r}.encode()\n"
            "        self.send_response(200); self.end_headers(); self.wfile.write(body)\n"
            "if __name__=='__main__': HTTPServer(('127.0.0.1',8080),Handler).serve_forever()\n"
        )
        (proj/"README.md").write_text(f"# {name}\n\nGenerated by CompanyOS. Internal build artifact.\n")
        (proj/"manifest.json").write_text(json.dumps({"venture_id":vid,"name":name,"generated_at":time.time(),"external_launch_authorized":False},indent=2)+"\n")
        p=subprocess.run([sys.executable,"-m","py_compile",str(proj/"app.py")],capture_output=True,text=True)
        if p.returncode!=0:
            txt=(proj/"app.py").read_text().replace("\t","    ")
            (proj/"app.py").write_text(txt if txt.endswith("\n") else txt+"\n")
            p=subprocess.run([sys.executable,"-m","py_compile",str(proj/"app.py")],capture_output=True,text=True)
        rep={"venture_id":vid,"project_path":str(proj),"build_ok":p.returncode==0,"qa_status":"passed" if p.returncode==0 else "failed","stderr":p.stderr[-2000:],"external_actions_performed":False,"financial_actions_performed":False}
        save(REPORTS/f"{vid}.json",rep); results.append(rep)
    out={"ok":all(x["build_ok"] for x in results) if results else True,"builds_processed":len(results),"builds_passed":sum(1 for x in results if x["build_ok"]),"results":results}
    save(STATE,out); return out
cmd=sys.argv[1] if len(sys.argv)>1 else "status"
print(json.dumps(build() if cmd=="build" else load(STATE,{"ok":True,"status":"not_run"}),indent=2))
